### ISSUE TITLE
This site can’t be reached. localhost refused to connect.

### ISSUE THREAD

**Issue by RameshKumarGogoi** [PlexRipper/PlexRipper#114]
I am new to docker. PlexRipper is running but I when open http://localhost:7000/setup, it shows "This site can’t be reached. localhost refused to connect".

**Comment by fxsth** [comment]
It'd be helpful if you describe how you set up your container.
In case you executed `docker pull plexripper/plexripper:latest`, you need to map ports (by adding `-p 7000:7000`) and probably need to mount volumes for download directory either (` -v /path/to/library:/library \`)

**Comment by EricLauber** [comment]
@expacc007 I ran the following for my container: `docker run -d -p 7000:7000 plexripper/plexripper`.

I did not map the volume for the download directory like @fxsth did, but I am running in Windows so my container's directory was available for browsing through Windows File Explorer.

**Comment by JasonLandbridge** [comment]
Yes indeed as @EricLauber mentioned, it's most likely due to the ports not mapped/exposed correctly. Will close this issue for now but re-open if you need more help

**Comment by aadilayub** [comment]
I'm struggling with this. I pulled the latest image and ran `docker run -d -p 7000:7000 plexripper/plexripper` but when I open localhost:7000 in my browser, it resets the connection
