### ISSUE TITLE
Selecting "Confirm" on the download dialog does not dismiss the dialog

### ISSUE THREAD

**Issue by EricLauber** [PlexRipper/PlexRipper#122]
I am running PlexRipper V0.8.7.

I browse to a server, find something I want to download, and select it. The "Are you sure" dialog appears, and I have an option to "Cancel" and "Confirm." When I select Confirm, the "Downloads" on the left side menu updates to show a new download is in progress... but the dialog stays up. I have to click outside of the dialog to dismiss it.

**Comment by talormanda** [comment]
Also having this issue.

**Comment by JasonLandbridge** [comment]
I just tried it in the latest v0.9.0 version and can confirm this has been fixed. Please re-open if the issue still remains
