### ISSUE TITLE
Connects to my plex account, sees my server, but won't connect.  "Status check" says "not checked yet"

### ISSUE THREAD

**Issue by tiny-e** [PlexRipper/PlexRipper#124]
Plex server version:  Version 1.28.0.5999
PlexRipper Version 0.8.7 (unraid docker container)

Setup seemingly went OK, but I don't see anything populating under my server (note the server and the PR are running in containers on the same box). 

Am I doing something wrong?  I'd like to have it connect to my own server for testing.

**Comment by tiny-e** [comment]
Revised title to be more accurate.

**Comment by Sack148** [comment]
I am seeing a similar issue. 
Clicking on "Check server Status" results in two errors that are shown in the developer console:
![grafik](https://user-images.githubusercontent.com/88580155/198023599-e081d5d1-3302-47da-8946-07054581c934.png)

**Comment by JasonLandbridge** [comment]
This has been fixed, it will now display a nicer error when the server happens to be offline. Please check out v0.9.0 and try it again
