### ISSUE TITLE
Is this project dead? 

### ISSUE THREAD

**Issue by tiny-e** [PlexRipper/PlexRipper#125]
I see issues back to June with no comments... wondering if it's still alive.

**Comment by JasonLandbridge** [comment]
I will most likely just change the project name to "NO THIS PROJECT IS NOT DEAD", everything I'm currently working on is happening in the dev branch. See [https://github.com/PlexRipper/PlexRipper/tree/dev](https://github.com/PlexRipper/PlexRipper/tree/dev) 

Last commit was a month ago, so you be the judge whether this project is dead or not.

**Comment by JasonLandbridge** [comment]
Just a quick word from the almighty PlexRipper creator, me. 

I'm really grateful for the issues raised and the seeming popularity of PlexRipper. I've said several times that I'm guarenteed to not abandon this project, which I'm still not planning on. However, work and life gets in the way but there is some good news. I will take a nice long break of several months starting this 1st November and will finally have the mental headspace to continue full time development on PlexRipper. 

I do apologize for not responding to issues but I will catch up with it this next weekend.

**Comment by tiny-e** [comment]
Thanks for the reply- I'm trying both the 'Stable' and 'Developer' containers (on unraid) -- both are giving me the same issue.  Based on the version number reported in the GUI, they may both be the same version (?).  

I may (or may not) have a unique case for my issue as I use Starlink as my ISP --but my plex server is reachable from outside by the official plex apps / web app as per normal.

**Comment by tiny-e** [comment]
Crap-- I see this came in under a different thread... not my intention.  Delete my comments as you deem appropriate.

**Comment by JasonLandbridge** [comment]
No worries, I've not yet published a new Docker container for the dev branch due to some basic functions not yet working. So at this point it would not yet be better than what is on the stable branch. No hard promise, but I will publish this new container this weekend and  go from there.

**Comment by JasonLandbridge** [comment]
>  No hard promise, but I will publish this new container this weekend and go from there.

Well this aged quite badly :laughing: The new release is now available on both dev and latest so I will close this issue!
