### ISSUE TITLE
PlexRipper version for a Windows 10 plex server Please!

### ISSUE THREAD

**Issue by batty1224** [PlexRipper/PlexRipper#131]
I could not find out how to make a suggestion for the windows 10 plex server version really would be nice to be able to use on my server

**Comment by JasonLandbridge** [comment]
Hey there, I'm not sure what you mean. Can your server not run Docker?

**Comment by batty1224** [comment]
No It don’t it runs on windows 10

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by batty1224** [comment]
No It don’t it runs on windows 10

**Comment by JasonLandbridge** [comment]
Sorry for the late response, so you have a PC that has windows 10 installed? In that case you can install Docker Desktop and then install PlexRipper from there. 

See: https://docs.docker.com/desktop/install/windows-install/

**Comment by craftpag** [comment]
#203
