### ISSUE TITLE
Mount Plex libr

### ISSUE THREAD

**Issue by gzowner** [PlexRipper/PlexRipper#139]
There any chance we can mount the Library it self?
https://github.com/pknw1/docker-mount-plex-libraries-FUSE/tree/main/Plex/Api

think if you can mange to impliment this in with your setup. could be possible and lot cleaner for those that just want to mount. 
Thanks

**Comment by JasonLandbridge** [comment]
I like the idea, and in hindsight I could have gone this way, but it doesn't fit into the long term goal of integration with Sonarr or Radarr so it's very unlikely PlexRipper will ever work like this.
