### ISSUE TITLE
Slow speeds?

### ISSUE THREAD

**Issue by talormanda** [PlexRipper/PlexRipper#144]
I am getting 5.39 KB/s when trying to download a 327 MB file. Is this intentional or is there something I need to do to unlock faster speeds? The server it's coming from is capable of at least 50 Mb/s up.

**Comment by Hemps38** [comment]
Same here. Best bet is to use saverr rather

**Comment by talormanda** [comment]
> Same here. Best bet is to use saverr rather

is this another plex-downloader?

**Comment by Hemps38** [comment]
https://github.com/ninthwalker/saverr

**Comment by JasonLandbridge** [comment]
Hi there, the above issue has been fixed in the latest release v0.9.0!

Also, here are several more alternatives to PlexRipper: [similar projects](https://www.plexripper.rocks/guides/overview/similar-projects)

Closing this issue now, but definitely make a new one if the problem still persists :+1:
