### ISSUE TITLE
validate to plex account error

### ISSUE THREAD

**Issue by milfer322** [PlexRipper/PlexRipper#170]
Hello!
The first congratz for the update!

I see error when I try login with my user.

Add log console.
![image](https://user-images.githubusercontent.com/17482316/204789900-3e84259a-2245-4a2c-870c-f43de3d23919.png)
The user and password is writed in the form.

Thanks so much!

**Comment by JasonLandbridge** [comment]
Hi, thank you very much!

Are you sure that you're filling in the username and password here?

![image](https://user-images.githubusercontent.com/15127381/204795637-36159de1-9cc8-4b4a-8cff-ffb6832162a8.png)

And do you happen to have two factor authentication enabled on your account?

**Comment by milfer322** [comment]
> Hi, thank you very much!
> 
> Are you sure that you're filling in the username and password here?
> 
> ![image](https://user-images.githubusercontent.com/15127381/204795637-36159de1-9cc8-4b4a-8cff-ffb6832162a8.png)
> 
> And do you happen to have two factor authentication enabled on your account?

Yes, I write the username and passwords in the fields marked x) and display Name too.
No, I dont have two factor auth.

Thanks so much!

**Comment by milfer322** [comment]
I can see the password has sended in the payload:
![image](https://user-images.githubusercontent.com/17482316/204830514-0da51e4c-d8ac-475c-83fc-e2683fe630f9.png)

**Comment by JasonLandbridge** [comment]
Sure no problem!

**Comment by JasonLandbridge** [comment]
This might be a duplicatie of https://github.com/PlexRipper/PlexRipper/issues/194 so I'm closing this one
