### ISSUE TITLE
Translate the various Download states correctly

### ISSUE THREAD

**Issue by talormanda** [PlexRipper/PlexRipper#176]
![image](https://user-images.githubusercontent.com/10092964/204867451-2d9fdd46-0a1c-4f89-ba94-0f6888a7414d.png)

It should say Download Finished, or just "Finished".

**Comment by ronan-allen** [comment]
I saw this also. I think a good schema would be: 
Downloaded  = All files downloaded. 
Completed = All files downloaded and merged.
