### ISSUE TITLE
refreshing library stuck on 25%

### ISSUE THREAD

**Issue by Hemps38** [PlexRipper/PlexRipper#178]
Any ideas why it gets stuck on refreshing a TV Show library, stuck at 25% and then never moves further.
Try Movies and it gets info easily enough.

**Comment by JasonLandbridge** [comment]
Hey, can you take a look at the logs? On what platform are you? Unraid?

**Comment by Hemps38** [comment]
Synology DSM + Docker + Plex Ripper v0.9.1
On 50/50Mb fibre

This is error I get?
12:18:28 [Warning] [RestSharpExtensions.SendRequestWithPolly] => Request: http://70.68.230.117:27453/library/sections/3/all failed, waiting 1 seconds before retrying again (1 of 2).

12:18:39 [Warning] [RestSharpExtensions.SendRequestWithPolly] => Request: http://70.68.230.117:27453/library/sections/3/all failed, waiting 2 seconds before retrying again (2 of 2).

12:18:51 [Error] [RestSharpExtensions.GenerateResponseResult] => StatusCode - 0: 

12:18:51 [Error] [RestSharpExtensions.GenerateResponseResult] => ErrorMessage - The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.:

**Comment by JasonLandbridge** [comment]
That means the server is offline or not connectable. Can you access the server in plex.tv? And is it online there? If it is online, then it has most likely to do with https://github.com/PlexRipper/PlexRipper/issues/108. I'm fixing that as we speak

**Comment by Hemps38** [comment]
Tested and can access the server fine in plex.tv, even tried playing something and no issues

**Comment by JasonLandbridge** [comment]
Thanks for confirming, then it is most likely the #108 issue. With the next update you will be able to select which connection to use for a PlexServer. So most PlexServers have 3 different connections you can use and PlexRipper will test all 3 and always use 1 that is working, that should resolve many other issues as well
