### ISSUE TITLE
2FA not working.

### ISSUE THREAD

**Issue by ruablack2** [PlexRipper/PlexRipper#180]
When adding a Plex account from a brand new instance I get the following:

When I use my normal password I get this error and it never asks for 2FA code.

````
11:17:14 [Debug] [PlexApi.PlexSignInAsync] => Requesting PlexToken for account *

11:17:14 [Debug] [PlexApiClient.SendRequestAsync] => Sending request to: https://plex.tv/api/v2/users/signin

11:17:15 [Error] [RestSharpExtensions.GenerateResponseResult] => Request to https://plex.tv/api/v2/users/signin failed with status code: 0 - : 

11:17:15 [Error] [RestSharpExtensions.GenerateResponseResult] => StatusCode - 0: 

11:17:15 [Error] [RestSharpExtensions.GenerateResponseResult] => ErrorMessage - No error message found: 

11:17:15 [Error] [RestSharpExtensions.GenerateResponseResult] => {"errors":[{"code":1029,"message":"Please enter the verification code","status":401}]}: 
````

When I put in my password+2fa code in the password field It then asks me for a 2FA code and I get an email saying new device logged in from plex. but when I put in the 2FA code on the gui I get this:

Before 2FA code entered:

```
11:17:26 [Debug] [PlexApi.PlexSignInAsync] => Requesting PlexToken for account *

11:17:26 [Debug] [PlexApiClient.SendRequestAsync] => Sending request to: https://plex.tv/api/v2/users/signin

11:17:27 [Debug] [RestSharpExtensions.GenerateResponseResult] => Created: 

11:17:27 [Debug] [RestSharpExtensions.GenerateResponseResult] => StatusCode - 201: 

11:17:27 [Information] [PlexApiService.PlexSignInAsync] => Successfully retrieved the PlexAccount data for user CB from the PlexApi

11:17:27 [Debug] [PlexAccountService.ValidatePlexAccountAsync] => The PlexAccount with displayName CB has been validated
```

After 2FA code is entered in web gui:

```
11:17:32 [Debug] [PlexApi.PlexSignInAsync] => Requesting PlexToken for account *

11:17:32 [Debug] [PlexApiClient.SendRequestAsync] => Sending request to: https://plex.tv/api/v2/users/signin

11:17:32 [Error] [RestSharpExtensions.GenerateResponseResult] => Request to https://plex.tv/api/v2/users/signin failed with status code: 0 - : 

11:17:32 [Error] [RestSharpExtensions.GenerateResponseResult] => StatusCode - 0: 

11:17:32 [Error] [RestSharpExtensions.GenerateResponseResult] => ErrorMessage - No error message found: 

11:17:32 [Error] [RestSharpExtensions.GenerateResponseResult] => {"errors":[{"code":1031,"message":"User could not be authenticated. This IP appears to be having trouble signing in to an account (detected repeated failures)","status":401}]}: 
```

**Comment by JasonLandbridge** [comment]
Yes that is correct, I happen to have fixed it today so it will be fixed with the next release. Also thanks for the clear bug report!

**Comment by fitur** [comment]
I'm prompted to enter my password, which gives the same result as @ruablack2. When I enter my password, immediately followed by the 2FA-code, the log says the authentication succeeded but then I'm prompted to enter my 2FA-code again and the log says:

> 10:52:18 [Error] [RestSharpExtensions.GenerateResponseResult] => Request to https://plex.tv/api/v2/users/signin failed with status code: 0 - : 
>10:52:18 [Error] [RestSharpExtensions.GenerateResponseResult] => StatusCode - 0: 
>10:52:18 [Error] [RestSharpExtensions.GenerateResponseResult] => ErrorMessage - No error message found: 
>10:52:18 [Error] [RestSharpExtensions.GenerateResponseResult] => {"errors":[{"code":1031,"message":"User could not be authenticated. This IP appears to be having trouble signing in to an account (detected repeated failures)","status":401}]}:

**Comment by chrisdecker08** [comment]
Is there a work around for this or an eta for the next release?

**Comment by pentafive** [comment]
I had the same issue with 2FA. My workaround was to turn off 2FA on Plex my account, complete the PlexRipper setup and then re-enable 2FA on the Plex account.

Would prefer to have 2FA working or a method to directly provide the AuthenticationToken.

**Comment by JasonLandbridge** [comment]
This seems to have been fixed in the latest release, see: https://github.com/PlexRipper/PlexRipper/issues/199#issuecomment-1468237936
