### ISSUE TITLE
Server not reachable (https fails, http would work)

### ISSUE THREAD

**Issue by Animizio** [PlexRipper/PlexRipper#183]
Hey, I try to add an plex server. Its added, but after testing I get server not reachable. It tried to connect with DNS fix.
The IP it shows has https. But if you use it in the browser the ssl fails and it only connects to http. So maybe we need to support http connections too in plex ripper. I think, if he would connect to http it will work.
If you have a possible solution or something I'm ready to test and help.
Thank you very much!

**Comment by JasonLandbridge** [comment]
See #108 , closing because duplicate
