### ISSUE TITLE
Suggestion: create issue templates and labels

### ISSUE THREAD

**Issue by pcn** [PlexRipper/PlexRipper#198]
It would help a lot to have suggested issue templates to give you the information you need up-front.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

Also, adding labels like "tv-shows" "movies" "downloads" "bug" "feature" etc. could help the organization.

**Comment by JasonLandbridge** [comment]
Great suggestions! I have added various issue templates, please try them out and any feedback is welcome! And for the labels, I'm making them as I'm organizing the issues but I will keep it mind
