### ISSUE TITLE
Cannot download a complete season of TV with 0.9.1

### ISSUE THREAD

**Issue by pcn** [PlexRipper/PlexRipper#199]
With 0.9.1 running I need the following steps to download a complete season of a show after the first attempt (a season won't fully download if e.g. an entire multi-season show is selected, or if an entire season is selected. Instead it will start, then get stuck at some point)

1. Navigate to the show
2. unfurl the show and season
3. Select all episodes in the season except for 1 episode
4. Download button, wait for download to complete
5. open the `/downloads` link in a separate tab
6. delete all of the completed entries
7. back in the `/tvshows/<number>/details/<number>` path, download the remaining single episode
8. continue to the next season

What I've observed:

If I don't delete the completed downloads, or if I try to continue by downloading an entire season, I only get this message:
```
16:18:38 [Debug] [PlexDownloadService.DownloadMediaAsync] => Attempting to add download task orders: System.Collections.Generic.List`1[PlexRipper.Application.DownloadMediaDTO]
```
and nothing else. If I select all but one episode, then that message appears, but the download begins.

**Comment by sopipari** [comment]
I am having the same issue and started digging in a bit.  I've been monitoring the docker performance on unraid and it looks like the docker instance is slowly eating up all the memory.  Gets to about 95% system memory used it gets stuck.  I've een had my instance outright crash a few times.

**Comment by JasonLandbridge** [comment]
I think I have fixed both these issues, TvShows should download better now and the memory problem might have been solved due to resources being better cleaned up now. 

A new release ([0.10.0-RC-1](https://github.com/PlexRipper/PlexRipper/releases/tag/v0.10.0-RC1)) is available now on both the [latest](https://hub.docker.com/r/plexripper/plexripper/tags) and [dev](https://hub.docker.com/r/plexripper/plexripper/tags) docker channels, which contains all the changes/fixes from the past several months. Let me know if this fixes the issues.

**Comment by pcn** [comment]
I've upgraded the container, but can't test the fix - after reconfiguring (2fa worked, 🚀 !) and reconnecting to the servers my account has access to, it just says "no libraries available" under the servers. I can confirm that the two servers are both online.

**Comment by JasonLandbridge** [comment]
Have you cleared the config folder of any previous files? And what do the logs say?

**Comment by pcn** [comment]
Interesting thought - I assumed that since it prompted me to reconfigure that the config was cleared, but no I  did not. After clearing out the old config, the servers are behaving normally. Going to test now.

**Comment by pcn** [comment]
And boom, that worked!

**Comment by JasonLandbridge** [comment]
> And boom, that worked!

That brings a proud tear to my eye, thanks for confirming!

**Comment by sopipari** [comment]
Can also confirm, seems to be fixed.  I'll be watching the memory utilization as I download some series over the next few days.
