### ISSUE TITLE
How install PlexRipper on Windows 10/11

### ISSUE THREAD

**Issue by craftpag** [PlexRipper/PlexRipper#203]
Hello!

This is a quick tutorial on how to get PlexRipper on a Windows computer.
First you will need to install docker desktop from [https://www.docker.com/products/docker-desktop/](url) 
(if don't know how to do that go on youtube)
Download the `YAML` file from [https://github.com/PlexRipper/PlexRipper/archive/refs/heads/master.zip](url) then open the zip and Copy the `docker-compose.yml` file 
Next go to your media folder where you have all your movies and tvshows you stream on plex.  
Paste in the `yml` file. (You can place the `YML` file where ever you want but it feels clean there)
 
![image](https://user-images.githubusercontent.com/94468418/224167942-57307779-6b57-471b-b377-c6069d3eca4c.png)

Open the file with the preferred text editor and change the paths to the windows downloads, movies and tvshows path:
Before
![image](https://user-images.githubusercontent.com/94468418/224168530-3f67b6cb-6a84-4185-9956-a85b0c2bb409.png)
After
![image](https://user-images.githubusercontent.com/94468418/224168782-9dfcd7f7-dc86-45b1-a178-047bb47611c8.png)
Save the file and open `Command Prompt`.
Change your directory to the path where you have the `docker-compose.yml` example:
![image](https://user-images.githubusercontent.com/94468418/224170278-9d728462-f72f-4a14-aba0-26862ff0016a.png)
If the files are on the C: disk you don't need to use `/d`.
Now you can start composing the `YML` file by typing this in the terminal:
![image](https://user-images.githubusercontent.com/94468418/224170957-2f3420a9-8e30-4f9e-9a46-e7d0bea58b2b.png)
Now docker will download and install PlexRipper and start it. When it is ready you can go to [http://localhost:7000/](URL) and boom! You are in. 

If you have a more efficient way of doing this please show me.
.....
craftpag

**Comment by JasonLandbridge** [comment]
Thanks for the write up! I'm on Linux so I don't have [Docker desktop](https://www.docker.com/products/docker-desktop/) available but I can maybe setup a Windows machine and try it out as well. 

The PlexRipper docker images are here: https://hub.docker.com/r/plexripper/plexripper/tags

**Comment by JasonLandbridge** [comment]
I finally got around to it, I created a guide with screenshots to install PlexRipper on a Windows machine: https://www.plexripper.rocks/guides/installation/windows

Closing this now in favor of that guide, feedback is very welcome!
