### ISSUE TITLE
Max Timeout of 10s for API may not be sufficient

### ISSUE THREAD

**Issue by Tripton** [PlexRipper/PlexRipper#205]
Hey,

Thanks for the nice project.
As I had a lot of problems with the master Branch (e.g. not all Servers found due to old API), I'm using the MoreFixes branch as it seems that you are using it for active development.

In this branch (I didn't try others) there is a limit of 10s for the API to respond (https://github.com/PlexRipper/PlexRipper/blob/76e106e4a4fd7e80835312e7c0cc88e0e3960445/src/PlexApi/PlexApiClient.cs#L29).
This limit wasn't sufficient in my case, as I'm connected to a relatively large plex server. 
This caused that the content wasn't visible and I couldn't rip it.
Increasing this limit to a higher value (for quick testing to 100s) made it work like a charm again.

This is just some feedback, so you might consider increasing the value or enabling configuration of it.

Additionally, I would like to report, that when downloading Series in the state branch, there seem to be some bug when merging the different parts. This results in the downloaded file being 0 bytes.
Maybe the following two logs help:
```
[Error] [FileSystem.Create:0] => The process cannot access the file '/TvShows/series/episode.mkv' because it is being used by another process.
```

```
[Error] [DirectorySystem.DeleteDirectoryFromFilePath:0] => Could not determine the directory name of path: /Downloads/TvShows/series.part1.mkv or the path contains files
```
If you can't consider this, as it's still under active development, I can understand this :)

Last but not least, I have a feature request for the future. Browsing through such a large library is difficult, as loading all the information is relatively slow. A search function would be very handy for this.

Again thanks for your work :)

**Comment by JasonLandbridge** [comment]
Hi there!

Thanks for the kind words! Just for you, I have made a new release (0.10.0-RC-1), available on both the [latest](https://hub.docker.com/r/plexripper/plexripper/tags) and [dev](https://hub.docker.com/r/plexripper/plexripper/tags) docker channels, which contains all the changes from the past several months. 

**Timeout issue**

Yeah good point! I have changed the default value to a max of 60 seconds, and then for the requests, which should complete faster, I have set the timeout lower. This is already included in the 0.10.0-RC-1 release

**Cannot access the file**

Coincidentally I have fixed this issue two days ago which is included in the 0.10.0-RC-1 release. Let me know if this has fixed it for you.

**Search**

Yes this is sorely needed, I figured I would first have the downloading etc working "properly" before adding these new features. Hopefully soon!

Cheers!
