### ISSUE TITLE
[BUG] - Can't get media list to sort in DESCENDING order

### ISSUE THREAD

**Issue by Balok-Fesarius** [PlexRipper/PlexRipper#236]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

v0.12.0

### Platform

Synology

### Browsers

Google Chrome

### Description

I'm trying to sort media (Table View) by 'Added At' DESCENDING, however list seems to sort ASCENDING no matter the direction of up/down arrow to the right of the column name.

### Reproduction steps

```bash
1. Click up/down arrow to the right of the column header in media (Table View)
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
N/a
```

**Comment by JasonLandbridge** [comment]
This is fixed in the [0.14](https://github.com/PlexRipper/PlexRipper/releases/tag/v0.14.0) release, it should be online in a few minutes!
