### ISSUE TITLE
💡 [REQUEST] - HTTPS support

### ISSUE THREAD

**Issue by beefycheddar** [PlexRipper/PlexRipper#237]
### Checks

- [X] I have searched the existing issue and my feature request does not exist!
- [X] I have tried out the latest development build and can confirm my feature request is not yet implemented!

### Describe the feature

I haven't found it in documentation yet, so if it is there, sorry for redundancy. 

Does plexripper support https only servers? I can only connect to http servers. This is a limitation for me.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by TheMinecraftGuyGuru** [comment]
this does need to be fixed, I have encountered a few servers I can't connect to, and after digging deeper, it is indeed because those servers do not permit http connections.

**Comment by republicandaddy** [comment]
Hi, I'm new to PlexRipper....

However, I'm running 0.14.0 on TrueNAS Scale.  I'm wondering if there's something going on in TrueNAS that's funky here.  I'm having the same issue above, but I see you fixed it on 0.13.0.  So, I've got it running on TrueNAS Scale which, in turn is running as a VM on my Proxmox Cluster.  Now, I'm wondering if the nesting is causing the issues.  Any thoughts?  I'm not even sure where to start, to be honest.

The server that doesn't connect is remote, one of my friends.  It works fine in plex both inside my network and from my phone using the cell network.
