### ISSUE TITLE
💡 [REQUEST] - prebuillt package with runtime

### ISSUE THREAD

**Issue by nephaste** [PlexRipper/PlexRipper#240]
### Checks

- [X] I have searched the existing issue and my feature request does not exist!
- [X] I have tried out the latest development build and can confirm my feature request is not yet implemented!

### Describe the feature

Hi thanks for this project

Any chance , to get prebuilt x64, arm64, armV7 package for non docker users ?

thanks a lot,

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by nephaste** [comment]
Hi 

Goal it is to propose a nativ Linux version on Qnap NAS and propose it on users over our repository www.myqnap.org
some people do not like use docker...

we need arm64, armv7 and x64 version... many dotnet apps are available with prebuilt runtime for differents archs : radarr, prowlarr ... or Jellyfin

here is an example how compile Jellyfin with dotnet runtime for x86_64 (intel/amd 64bit)

 dotnet publish Jellyfin.Server --configuration Release --self-contained --runtime linux-x64 --output="/tmp/jellyfin" "-p:GenerateDocumentationFile=false;DebugSymbols=false;DebugType=none;UseAppHost=true"

thanks for your help..

**Comment by JasonLandbridge** [comment]
Thanks for the explanation! I'm very open to pull requests that can implement this, but I'm afraid it would take too much time if I have to do it, due to not owning any hardware that can be used to test if the builds are working. 

Ideally it would be a GitHub Action that gets triggered on every release, I can at least help with that but I definitely need someone to take this on.

**Comment by soundtechscott** [comment]
can we get a windows executable version ?

**Comment by frosit** [comment]
I think this is defenitely one for the roadmap, docker is nice and brings flexibility but for anything except the dockerish addon kinda platforms, it's basically a lot of overhead. I just joined this project to help out with these kind of things. Though packaging dotnet applications would be new to me, I think it can be done. Multi arch builds is on my todo list as well so if anyone has some good references I can take a look at from a learn by example perspective, that would be appreciated 😄

Thanks @nephaste you gave me a starting point. @soundtechscott if we go in this direction, i don't see why not.

**Comment by frosit** [comment]
I have done a few experiments and managed to get working prebuilds for OSX, linux, windows etc. However, since we're running this application from a different host, we have to change a few things in the applications. For example, the way paths/directories are handled. I'm already working on this.

**Comment by JasonLandbridge** [comment]
This should now work with the latest dev build. Please see: https://github.com/PlexRipper/PlexRipper/issues/363
