### ISSUE TITLE
💡 [REQUEST] - Checkbox Amount view

### ISSUE THREAD

**Issue by Ratte443** [PlexRipper/PlexRipper#241]
### Checks

- [X] I have searched the existing issue and my feature request does not exist!
- [X] I have tried out the latest development build and can confirm my feature request is not yet implemented!

### Describe the feature

Im trying to sync a Plex Libary with my Server what is running PlexRippper,
the library has more than 20k movies, and it's not possible to download in batches.
It would be helpful if we can choose an amount per site.

Example:
Show amount: 50 | 100 | 500 | 1000 or custom
By choosing the amount, each site has the number of items. 

Actually, there is no way for me to sync that library because it is that big, doing 1 by 1 with hand makes too much hussle.

Thank you!

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by JasonLandbridge** [comment]
Hi there,

You can switch to table view and select all movies/tv shows by clicking the checkbox at the top.

Can you try that?

**Comment by Ratte443** [comment]
That is precisely what I did. But the library has 20k items.  After I start it, web view is not loading correctly anymore and downloads not running. Software gets stuck. I hope you can help me find a way, to get this library.

**Comment by JasonLandbridge** [comment]
Okay just to check, the library view is working correctly? As in you can see everything and select all media to download?

And I think the download view is not optimized yet to handle such a huge number of downloads so I will need to solve that first. 

I think for now you need to do it in batches until at least PlexRipper can handle such huge number of downloads

**Comment by Ratte443** [comment]
> Okay just to check, the library view is working correctly? As in you can see everything and select all media to download?
> 
> And I think the download view is not optimized yet to handle such a huge number of downloads so I will need to solve that first.
> 
> I think for now you need to do it in batches until at least PlexRipper can handle such huge number of downloads

Yea it would be fine if I can do in batches, but the only option now is to mark the checkboxes manually. 
So i need to click 100 times a checkbox, then start. And same again many times, I hope you can provide a hotfix or optimization for that use case.

**Comment by JasonLandbridge** [comment]
What I can do is make a selector button where you put in the index range, e.g: select 100 to 200. That should make it way easier to select stuff and then you only need to remember the last index you downloaded. I will work on it tomorrow or there after.

**Comment by Ratte443** [comment]
> 

perfect, that would help me alot!

**Comment by Ratte443** [comment]
Any news when you have it done? I would be happy when I can speed up that work with a donation :-)

**Comment by JasonLandbridge** [comment]
Haha thanks for the offer but maybe in the future! I'm honestly in the middle of interviewing for a position as a freelance developer so my mind has been occupied with that. You can follow this [branch](https://github.com/PlexRipper/PlexRipper/tree/Fixes) for the progress but it is something I'm working on right now!

Maybe it's done today, I will let you know!

**Comment by JasonLandbridge** [comment]
@Ratte443 I used a slider/range effect where you can drag your selection. But I think it's missing some quality of life things, do you have any suggestions?

[Demo](https://quasar.dev/vue-components/range#standard)

![image](https://github.com/PlexRipper/PlexRipper/assets/15127381/517b03a7-2992-497b-b681-a0cb2f7819ab)

**Comment by Ratte443** [comment]
> @Ratte443 I used a slider/range effect where you can drag your selection. But I think it's missing some quality of life things, do you have any suggestions?
> 
> [Demo](https://quasar.dev/vue-components/range#standard)
> 
> ![image](https://user-images.githubusercontent.com/15127381/248042333-517b03a7-2992-497b-b681-a0cb2f7819ab.png)

Looks good, maybe you can add manual typing numbers aswell. 
To have both options, the manual text box for the numbers and the slider should be synchronized. 

Then 10/10, but if not, I'm also happy with that.

**Comment by JasonLandbridge** [comment]
Yes that should be easy to do! So input is coming, in the mean-time I added some buttons:

![image](https://github.com/PlexRipper/PlexRipper/assets/15127381/62eb198b-eaea-4718-ad8b-3211c5007486)

Especially with these huge libraries it's a pain to try to accurately set the range of selection so I figured I add some buttons. I'm also trying to think of a way to save the selection range so you can easily keep continuing from where you left off.

**Comment by Ratte443** [comment]
Absolutely awesome!

**Comment by JasonLandbridge** [comment]
Okay saving the selection range is a bit of work, because then I need to store it for every library. It's possible but yeah, let's release this first. 

![image](https://github.com/PlexRipper/PlexRipper/assets/15127381/389c225a-45b2-4a30-aa13-6e649d20aa58)

The index numbers are based on these: 

![image](https://github.com/PlexRipper/PlexRipper/assets/15127381/4554a94e-7507-4d87-81ba-2e72920fc0ee)

I will have a release soon!

**Comment by JasonLandbridge** [comment]
I've created the [0.14](https://github.com/PlexRipper/PlexRipper/releases/tag/v0.14.0) release, it should be online in a few minutes!
