### ISSUE TITLE
[REQUEST] - Use the filename of the original media file when downloading and creating

### ISSUE THREAD

**Issue by rsockanc** [PlexRipper/PlexRipper#250]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

0.14.0-DEV.1

### Platform

Windows

### Browsers

Google Chrome

### Description

If the source file is at as seen in the status icon of a current download:

File Name:  \\192.168.1.5\media\Movies\Mighty Ducks (2021)\Mighty Ducks (2021) Bluray-1080p.mkv

Then the actual file name saved after merge on the destination will be " \\192.168.1.5\media\Movies\Mighty Ducks (2021)\Mighty Ducks (2021) Bluray-1080p.mkv"

Expected would be file name saved is "Mighty Ducks (2021) Bluray-1080p.mkv" in a folder called "Mighty Ducks (2021)"

### Reproduction steps

```bash
Download from a Windows Plex server where the source media is on a network path.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
NA
```

**Comment by JasonLandbridge** [comment]
I will turn this into a task where PlexRipper will start using the filename that it's ripping from as that is always valid instead of trying to create it's own unique name.

**Comment by BRAYDIN72** [comment]
I think I have the same issue. I am going to try to describe this the bet I can. On my friends server I am trying to download "All of Me" I go to his server, find the movie, click download then confirm. The download page looks like this.

![Screenshot 2024-01-31 104629](https://github.com/PlexRipper/PlexRipper/assets/42328309/2c2949a7-5d9d-4c94-84c7-4bbda53606e5)
 It downloads the entire file. and then gives me this error.
![Screenshot 2024-01-31 103957](https://github.com/PlexRipper/PlexRipper/assets/42328309/084803e4-79a9-4eeb-8dcc-f07ff67cfabc)
Notice the M:\Plex Media in the file name , that isn't in any of my configs, that's his path on his server. It's not even that way in the first screenshot. 
Anyone have a fix?

**Comment by JasonLandbridge** [comment]
This has been fixed
