### ISSUE TITLE
[BUG] - preferred server connection not shown

### ISSUE THREAD

**Issue by LtCMDstone** [PlexRipper/PlexRipper#253]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

V0.14.0-dev.1

### Platform

Linux

### Browsers

Google Chrome, Microsoft Edge (LOL)

### Description

The preferred connection settings is not shown in the UI.
It's saved in the DB but not shown in the UI.

also the httpsRequired flag should be represented there and be used for the connection (see in the log section)

### Reproduction steps

```bash
1. Select a preferred connection
2. reload page
3. goto connections
4. selected not shown
```

### Screenshots

![image](https://github.com/PlexRipper/PlexRipper/assets/25282375/a9e05db6-599e-41b3-98d0-c7ca3ff74520)

![image](https://github.com/PlexRipper/PlexRipper/assets/25282375/5a6acffb-d07d-498c-b525-113b470012eb)

### Logs

```bash
08:55:17 [Debug] [PlexApi.GetServerStatusAsync:85] => Requesting PlexServerStatus for http://***MASKED***/
08:55:17 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: http://***MASKED***:32400/identity
08:55:18 [Warning] [RestSharpExtensions.SendRequestWithPolly:51] => Request to: http://***MASKED***/identity failed, waiting 1 seconds before retrying again (1 of 1)
08:55:19 [Error] [RestSharpExtensions.ParsePlexErrors:159] => Request to http://***MASKED***:32400/identity failed with status code: 0 - An error occurred while sending the request.

 - Metadata:
 -- StatusCode - 0
 -- ErrorMessage - An error occurred while sending the request.
08:55:19 [Debug] [CreatePlexServerStatusCommandHandler.Handle:27] => Creating a new PlexServerStatus ***MASKED*** in the database for 1
```

**Comment by JasonLandbridge** [comment]
Thanks for the report! It has been fixed, it will go live in the next version :+1:
