### ISSUE TITLE
[BUG] - qemu: uncaught target signal 11 (Segmentation fault) - core dumped

### ISSUE THREAD

**Issue by CodeSpent** [PlexRipper/PlexRipper#254]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

v0.14.0

### Platform

Mac

### Browsers

Other (Specify in description)

### Description

Issues running Docker container on Apple Silicon systems.

```
2023-08-28 14:36:03 
2023-08-28 14:36:03 18:36:02 [Information] [PlexRipperHost.Setup:18] => Currently running on Linux
2023-08-28 14:36:04 
2023-08-28 14:36:04 18:36:04 [Information] [PlexRipperDbContext.Setup:173] => Setting up the PlexRipper database
2023-08-28 14:36:11 
2023-08-28 14:36:11 18:36:11 [Information] [PlexRipperDbContext.Setup:179] => Attempting to migrate database
2023-08-28 14:36:15 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

### Reproduction steps

```bash
1.) Pull plexripper image from Dockerhub.
2.) Run container with plexripper.
3.) Observe error as database attempts to migrate.
```

### Logs

```bash
2023-08-28 14:36:03 
2023-08-28 14:36:03 18:36:02 [Information] [PlexRipperHost.Setup:18] => Currently running on Linux
2023-08-28 14:36:04 
2023-08-28 14:36:04 18:36:04 [Information] [PlexRipperDbContext.Setup:173] => Setting up the PlexRipper database
2023-08-28 14:36:11 
2023-08-28 14:36:11 18:36:11 [Information] [PlexRipperDbContext.Setup:179] => Attempting to migrate database
2023-08-28 14:36:15 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```
```

**Comment by CodeSpent** [comment]
This is related to #137 I will be looking into adding arm64 compatibility to this image.

**Comment by JasonLandbridge** [comment]
@CodeSpent thank you very much! Can you open a PR on the dev branch? I'm not sure what you have so far but ideally this could become part of the deploy pipeline such that a new image will be generated automatically on subsequent releases

**Comment by CodeSpent** [comment]
@JasonLandbridge I'm gonnas say use `docker buildx` for multi-arch support & release different tags for each architecture. Since we can validate everything as working from a native build, BuildX should get it  set up.

Something like this.
```
 docker buildx build --platform linux/amd64,linux/arm64 -t image:latest --output=type=registry 
 ```
 
 I'll work on a PR to adjust dependencies & GH Actions tasks to add this step.

**Comment by CodeSpent** [comment]
Quick update, I've been still working on this through the existing Github actions, but bandwidth for free-time projects dwindles. Github provides an image for `buildx` in Github Actions you can leverage that'll let you build for all platforms without a lot of overhead.

If anyone gets to implementing that before me, by all means, otherwise as soon as I get a few free hours I'll wrap this up! :)

**Comment by JasonLandbridge** [comment]
@CodeSpent I'm definitely not a DevOps guy so you're work here is greatly appreciated! Let me know if I can help out!

**Comment by frosit** [comment]
I have been working on multi-arch builds and got the same error as you reported here when trying to build ARM on a single host. It is probably due to the qemu emulation as the buildx builds using a SSH node (my Pi4) did go through. Are you able to build the image on your mac? I unfortunately don't have a newer mac.

**Comment by belthesar** [comment]
I went ahead and grabbed latest dev and attempted to build an image on my MacBook Pro running an Apple Silicon M1 Pro. Build succeeded and the container does start, so it appears to be functional. May be worthwhile exploring interactions with dotnet, qemu, and Docker (this project can't be the only one experiencing these kinds of issues).

**Comment by JasonLandbridge** [comment]
This should now work with the latest dev build. Please see: https://github.com/PlexRipper/PlexRipper/issues/363
