### ISSUE TITLE
[BUG] - High CPU Usage When Series Download and Download Page Tabs Are Open

### ISSUE THREAD

**Issue by Whitedoteu** [PlexRipper/PlexRipper#256]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

V.14.0-DEV.1

### Platform

Unraid

### Browsers

Google Chrome

### Description

I have two tabs open in my browser: one for the series I'm downloading and another for the download queue page. When I switch to either of these tabs, my CPU usage spikes significantly. 

I've attached a screenshot for reference.

Upon investigating, it seems the issue is related to animations on these pages. Terminating the animation process via Task Manager resolves the issue and returns CPU performance to normal levels, albeit without background animation.

Is this a known issue, or is there any workaround for this?

Regarding the Version:
In Docker I'm using latest. 
But on the Webpage (top left) it sad: V.14.0-DEV.1

### Reproduction steps

```bash
1. Go to 'weppage tab'
2. CPU 100%
3. Remove Background-Canvas
3.1 Or kill Process in Taks-Manager
4. CPU a lot better
```

### Screenshots

```bash
![Taskmgr_5M4Ycx5Nqm](https://github.com/PlexRipper/PlexRipper/assets/16068109/8b903df5-0a7c-43cc-a152-fc1e388eb736)
![Taskmgr_y8pRWKlYvs](https://github.com/PlexRipper/PlexRipper/assets/16068109/3e2197d2-44d8-49c2-b66f-ae1cc0d2ee23)
```

### Logs

```bash
Seems to be a Frontend Issue. Did not find anything regarding the Topic in the Log.
```

**Comment by alafad** [comment]
Hey @Whitedoteu,

I can't reproduce your issue with the CPU spikes with Firefox 118, but if I have a big library and a large queue i have a mass of memory usage...

Could you please provide us a performance recording with the DevTools from chrome?

Another Off-topic Question: Which GER Plex provider could you recommend?

**Comment by Whitedoteu** [comment]
Hi alafad, 

https://www.elitepvpers.com/search/?q=plex+share&sa=

I using an alternative Tool now. 
A lot worse search but a lot better and stable downloader. 

I'm going to add a log next time i'm using it.

**Comment by JasonLandbridge** [comment]
> a lot better

Auch, what is this better tool you speak of?

**Comment by Whitedoteu** [comment]
Removing the animation would be great.

If you don't experience the issue with the animation on Firefox, perhaps Firefox itself might also perform better for downloads.

However, I've had numerous issues with merges not working or getting stuck, among other things.

I found https://github.com/fxsth/pledo. 
This has been working a lot better for me. Consistency is key here.
But if both were to work correctly, I would choose PlexRipper for its superior interface.

Sadly, I'm not familiar with C#, so helping or fixing it myself is not an option for me.

**Comment by JasonLandbridge** [comment]
All the points you're raising are very valid! I will keep working on PlexRipper and hopefully you can give it another shot in a while. 

Thanks for the alternative, it's nice to see more options besides PlexRipper. I will add it to the website: [similar projects](https://www.plexripper.rocks/guides/overview/similar-projects)

**Comment by JasonLandbridge** [comment]
The background animation has been made toggable here: https://github.com/PlexRipper/PlexRipper/pull/275
