### ISSUE TITLE
Inconsistent Download Speeds - Download stops every 60 seconds

### ISSUE THREAD

**Issue by xXSalamanderXx** [PlexRipper/PlexRipper#258]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

v0.14.0

### Platform

Windows

### Browsers

Brave

### Description

When downloading files, it runs fast and at consistent speeds for about 60 seconds, then the download speed goes to literally 0 kbps for the next 60 seconds and then starts up again. So basically, its 1 minute on, 1 minute off. 

My internet connection is always reliable and consistent, so I know for sure its specific to plex ripper.

This is running from a docker container on windows,

I'd appreciate it if you could look into this.

Thanks

### Reproduction steps

```bash
Already explained
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
.
```

**Comment by JasonLandbridge** [comment]
Closing this due to the age, if this is still an issue then reopen please
