### ISSUE TITLE
💡 [REQUEST] - Search text box to look for the movie you want to download vs navigate to the letter and scroll.

### ISSUE THREAD

**Issue by ril3y** [PlexRipper/PlexRipper#259]
### Checks

- [X] I have searched the existing issue and my feature request does not exist!
- [X] I have tried out the latest development build and can confirm my feature request is not yet implemented!

### Describe the feature

I would like to be able to search for a file I want do download vs navigate.  100tb servers take a while to find the right movies to download etc.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by JasonLandbridge** [comment]
Closing this in favor of https://github.com/PlexRipper/PlexRipper/discussions/337
