### ISSUE TITLE
[BUG] - Slow responsiveness and a cut off value

### ISSUE THREAD

**Issue by soundtechscott** [PlexRipper/PlexRipper#260]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

14

### Platform

Windows

### Browsers

Google Chrome

### Description

Very slow response when clicking
and some things get cut off by window/table size

you shoudl probably remove the in motion background... its slows down the browser massively
I used chromes built in inspector to remove the background element, and its drastically more responsive...
like 4x faster when navigating

also the "download segments, gets chopped off by the windows size and location, so you cant see the numbers

![image](https://github.com/PlexRipper/PlexRipper/assets/51548286/d981f060-5cf9-49d1-b213-fc008accd1fa)

### Reproduction steps

```bash
delete background
look at download segmnets visually
```

### Screenshots

```bash
screenshots included in main post
```

### Logs

```bash
no logs needed for this
```

TODO:
- [x] #269
- [x] #270

**Comment by JasonLandbridge** [comment]
TODO:
- [ ]  Add option to toggle off the animated background
- [ ] Fix the value cut-off

**Comment by JasonLandbridge** [comment]
Thanks for the report! I have added an option to disable the animated background. See https://github.com/PlexRipper/PlexRipper/pull/275

Disabling the animation can be done here:

![image](https://github.com/PlexRipper/PlexRipper/assets/15127381/6d8c8807-1a4c-4cf0-aac5-c13be1725d12)

The fix will go live in the next stable version, but the PlexRipper dev version will have it already
