### ISSUE TITLE
[BUG] - typo in container paths leads to wrong mounts

### ISSUE THREAD

**Issue by soundtechscott** [PlexRipper/PlexRipper#261]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

0.14

### Platform

Windows

### Browsers

Google Chrome

### Description

windows Save paths arent where downloads are saved??
where are they actually going while they are downloading?
I followed the instructions on the plexripper webpage and selected paths on my hard drive... but nothing is saved there??
I followed this example in the plexripper guides
![image](https://github.com/PlexRipper/PlexRipper/assets/51548286/7d8f29e8-8dd6-4db2-97fa-6e490d201eb2)

![image](https://github.com/PlexRipper/PlexRipper/assets/51548286/a4a31de8-d6b1-4f8f-a3f1-c1a328b404df)

![image](https://github.com/PlexRipper/PlexRipper/assets/51548286/00a50cf7-7446-4c96-a0d7-1aa58e8ab649)

where do the docker containers use for their file structure in a windows OS?
where in wondows are they saving while downloading?
where in windows are they writing to when they merge the pieces and save the final file?

### Reproduction steps

```bash
click on the directories that you selected in setup...
no files exist
```

### Screenshots

```bash
screenshots included in main post
```

### Logs

```bash
there are no logs
```

**Comment by JasonLandbridge** [comment]
Hey, I can already see you misspelt the Download path here: 
![image](https://github.com/PlexRipper/PlexRipper/assets/15127381/59c35300-b868-4408-8db7-39977f5eb279)

**Comment by frosit** [comment]
I think this issue can be closed? Pretty sure the problem is in the spelling, current setup does not allow alternate paths on the container side as the application expects them. Making typo's will cause a wrong directory to be mounted. More flexibility in paths is currently in development in #266.

**Comment by JasonLandbridge** [comment]
@frosit Agreed!
