### ISSUE TITLE
[BUG] - High CPU usage when PlexRipper is open in Google Chrome

### ISSUE THREAD

**Issue by soundtechscott** [PlexRipper/PlexRipper#262]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

.14

### Platform

Windows

### Browsers

Google Chrome

### Description

Extremely High CPU Usage when localhost window is open

![image](https://github.com/PlexRipper/PlexRipper/assets/51548286/2d34d336-8642-4d72-8759-cb610badad96)

### Reproduction steps

```bash
open Chrome, load weblink to localhost:7000
look at cpu usage
will use as much cpu as is available causing 100% cpu usage all the time while window is opsn
```

### Screenshots

```bash
screen shot in main text
```

### Logs

```bash
no logs to provide
```

**Comment by JasonLandbridge** [comment]
This might be fixed in: https://github.com/PlexRipper/PlexRipper/issues/269

Needs confirmation when the fix is live
