### ISSUE TITLE
💡 [REQUEST] - custom server access urls

### ISSUE THREAD

**Issue by frosit** [PlexRipper/PlexRipper#278]
### Checks

- [X] I have searched the existing issue and my feature request does not exist!
- [X] I have tried out the latest development build and can confirm my feature request is not yet implemented!

### Describe the feature

I have been experimenting with plex setups and connectivity and it seems like PlexRipper gets it's server URL's from the main plex server (plex.tv), and it seems that only returns the URL's for external communication, which are public URL's.

![Screenshot 2023-11-14 221209](https://github.com/PlexRipper/PlexRipper/assets/4974910/5dab6b9d-4862-4b13-aef0-c0fb6d67c77c)

As I was investigating #272 I noticed that you can also configure custom URL's under Network. But these are not provided by plex.tv so plexripper doesn't know of them?

![Screenshot 2023-11-14 221255](https://github.com/PlexRipper/PlexRipper/assets/4974910/d4803803-8a1e-4a8f-99d4-531ba2a202e1)

But I don't like exposing machines from my LAN because I like to mess around so for security and all sorts of flexibility, I prefer to use private networks. like: Tailscale, Wiregaurd, Zerotier etc. 

And it works :

![Screenshot 2023-11-14 221944](https://github.com/PlexRipper/PlexRipper/assets/4974910/463101ba-dd23-4a12-b275-0fb595836b14)

But...

![Screenshot 2023-11-14 222102](https://github.com/PlexRipper/PlexRipper/assets/4974910/d47d6d49-e9b3-4bdb-b2f4-50edb08e3969)

So I assume it works this way as it doesn't seem to update, so it would be nice if you could __enter a custom URL at the preffered connections tab for the server screen__.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by JasonLandbridge** [comment]
Implemented here: https://github.com/PlexRipper/PlexRipper/pull/384
