### ISSUE TITLE
💡 [REQUEST] -Sync TV shows  between servers automatically 

### ISSUE THREAD

**Issue by raulmad6600** [PlexRipper/PlexRipper#286]
### Checks

- [X] I have searched the existing issue and my feature request does not exist!
- [X] I have tried out the latest development build and can confirm my feature request is not yet implemented!

### Describe the feature

It would be great if you could choose one of your available servers as the main source and the other as the destination. Then select the TV shows that you want to sync.  Periodically will check  if there is a new episode or season (comparing  with destination ) on the main server and process with the download 

### Additional information

- [x] Would you be willing to help implement this feature?
- [x] Does this feature have a potential to break existing features?

**Comment by JasonLandbridge** [comment]
Thanks for the feature idea, a similar feature will be implemented in combination with Sonarr/Radarr, so I'm closing this in favor of https://github.com/PlexRipper/PlexRipper/discussions/400
