### ISSUE TITLE
💡 [REQUEST] - Search function

### ISSUE THREAD

**Issue by chris-20** [PlexRipper/PlexRipper#287]
### Checks

- [X] I have searched the existing issue and my feature request does not exist!
- [X] I have tried out the latest development build and can confirm my feature request is not yet implemented!

### Describe the feature

A search function to look for specific films in a a media library would be great.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by talormanda** [comment]
Would love a search function

**Comment by JasonLandbridge** [comment]
Dupplicate: https://github.com/PlexRipper/PlexRipper/issues/259
