### ISSUE TITLE
[BUG] Media size misrepresentation

### ISSUE THREAD

**Issue by informatdcs** [PlexRipper/PlexRipper#304]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

latest

### Platform

Windows

### Browsers

Chromium

### Description

mediasize is divided by 1000 3 times by pretty bytes, my language settings are in english but when I look into a movie with mediaSize "5060276853" it says 5.06GB when it is 4.71GB, I'm guessing this is broken here.

### Reproduction steps

```bash
Just see any media size and compare it to downloaded content
```

### Logs

```bash
no logs
```

**Comment by JasonLandbridge** [comment]
I think that is the difference between decimal and binary:
![image](https://github.com/user-attachments/assets/c7c4c47b-d16d-4ed4-abd6-1632b93930e3)

I could maybe add an option to display either formats
