### ISSUE TITLE
Failing merge with commas or semicolons

### ISSUE THREAD

**Issue by Firehawke** [PlexRipper/PlexRipper#312]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

v0.14.0

### Platform

Synology

### Browsers

Vivaldi

### Description

Downloads parts but fails to merge; appears to be related to commas or semicolons  in the filename.

### Reproduction steps

```bash
1. Download episode S01E22 or S01E26 of How a Realist Hero Rebuilt the Kingdom.
2. It will get stuck on the merging task, you'll get the error that the location doesn't exist. The parts to merge DO exist in the downloads folder.

Note that other episodes from the same set work fine, as do a lot of other materials on the Plex server. It's only a few things that seem to break.
```

### Screenshots

![image](https://github.com/PlexRipper/PlexRipper/assets/34792592/f866b750-8d52-4d41-9193-61f66a192e69)

### Logs

```bash
Doesn't seem to appear in the log.
```

**Comment by Firehawke** [comment]
Seems like colons and slashes also break it, based on further testing.

**Comment by JasonLandbridge** [comment]
Due to the age of this issue I'm closing it as a big update ([0.15-0.17](https://github.com/PlexRipper/PlexRipper/releases)) with a years worth of updates and fixes has been released. Please let me know if this is still an issue!
