### ISSUE TITLE
💡 [REQUEST] - Server Alias / Nick Name / Hide

### ISSUE THREAD

**Issue by mneimeyer** [PlexRipper/PlexRipper#314]
### Checks

- [X] I have searched the existing issue and my feature request does not exist!
- [X] I have tried out the latest development build and can confirm my feature request is not yet implemented!

### Describe the feature

Be able to assign a nick name or alias to a server.

I'd love to be able to assign a nick name or alias to a server rather than rely on the name given by the server owner. If the nick name is set to "" (empty string) then the server does not appear in the list of servers. Would need to be able to manage the list somewhere else.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by JasonLandbridge** [comment]
The next release will include a way to add a server alias, hiding certain servers would be easy but would require an easy way to unhide them as well which requires more effort. I will keep this issue open for now

**Comment by JasonLandbridge** [comment]
Completed in #324
