### ISSUE TITLE
[BUG] - PlexRipper-Development on unraid error

### ISSUE THREAD

**Issue by bleriaf** [PlexRipper/PlexRipper#315]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

last

### Platform

Unraid

### Browsers

Other (Specify in description)

### Description

Hello, i'm trying to download the PlexRipper-Development on unraid, however when launching the docker it comes with the following error:
You must install or update .NET to run this application.

App: /app/PlexRipper.WebAPI.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.11-x64
You must install or update .NET to run this application.

App: /app/PlexRipper.WebAPI.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.11-x64
You must install or update .NET to run this application.

App: /app/PlexRipper.WebAPI.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.11-x64
You must install or update .NET to run this application.

App: /app/PlexRipper.WebAPI.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.11-x64
You must install or update .NET to run this application.

App: /app/PlexRipper.WebAPI.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.11-x64

### Reproduction steps

```bash
Download Plexripper's developement repository on unraid and it will give this issue
```

### Screenshots

```bash
https://i.imgur.com/QOdMPHd.png
```

### Logs

```bash
text  error  warn  system  array  login  

You must install or update .NET to run this application.

App: /app/PlexRipper.WebAPI.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.11-x64
You must install or update .NET to run this application.

App: /app/PlexRipper.WebAPI.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.11-x64
You must install or update .NET to run this application.

App: /app/PlexRipper.WebAPI.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.11-x64
You must install or update .NET to run this application.

App: /app/PlexRipper.WebAPI.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.11-x64
You must install or update .NET to run this application.

App: /app/PlexRipper.WebAPI.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.17 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.11-x64
```

**Comment by chrisdecker08** [comment]
This is also affecting me

**Comment by frosit** [comment]
Woops, you guys are using docker right? Just latest or a specific version? Seems like our docker image has dotnet 7 installed but uses dotnet 8. I had been struggling with this problem trying to build images for regular and arm but never finished this due to these issues. But the dev branch builds and uploads docker images automatically so my guess is @JasonLandbridge updated to dotnet 8 but our docker images are still on 7?

**Comment by bleriaf** [comment]
> Woops, you guys are using docker right? Just latest or a specific version? Seems like our docker image has dotnet 7 installed but uses dotnet 8. I had been struggling with this problem trying to build images for regular and arm but never finished this due to these issues. But the dev branch builds and uploads docker images automatically so my guess is @JasonLandbridge updated to dotnet 8 but our docker images are still on 7?

yes that's right, using docker

**Comment by JasonLandbridge** [comment]
Yes, this has now been fixed!
