### ISSUE TITLE
💡 [Feature] - <Sonarr/Radarr Sabnzbd Download Client Integration for Import Automation>

### ISSUE THREAD

**Issue by Pleasuremanrx** [PlexRipper/PlexRipper#317]
### Checks

- [X] I have searched the existing issue and my feature request does not exist!
- [X] I have tried out the latest development build and can confirm my feature request is not yet implemented!

### Describe the feature

So after plexripper downloads the files one would have to manually sort them via copy & paste (drag and drop) in order to put the items in their respective folders that sonarr/radarr has already created but if Sabnzbd is integrated as download client same way it is setup in settings of radarr/sonarr then it would automatically import them. 
"automatically import completed downloads from download client"
![image](https://github.com/PlexRipper/PlexRipper/assets/174928980/6629ec9a-2bdf-494e-8680-e3b0bbd93220)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by Pleasuremanrx** [comment]
excuse my lack of awareness with how sabnzbd works it appears it only allows or accepts nzb files/usenet did you also discover this and just wondering if you decided to go forward with the general idea of automatically importing completed downloads from a download client

was grinning ear to ear when I saw this get some traction and now that im developing my own app realizing how the moving parts actually work but im curious to know your plans

guessing plexripper could have option to be seen as a download client in sonarr/radarr to allow it to sort the downloaded files in the watched folders...disregard been up all night working on this app and realizing I phrased it wrong but you got the gist lol

**Comment by JasonLandbridge** [comment]
@Pleasuremanrx Yo, yeah we are in the planning stages now and the discussion is centered here: https://github.com/PlexRipper/PlexRipper/discussions/400#discussioncomment-11553719

Please add any wisdom you may have about this there and I can add it to the overall vision.

Thanks!
