### ISSUE TITLE
[Security] - Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [PlexRipper/PlexRipper#374]
### Checks

- [x] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

Latest

### Platform

Linux

### Browsers

Google Chrome

### Description

Greetings PlexRipper maintainers,

Github Security Lab has found a potential vulnerability in PlexRipper. Please open [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) or provide us a private point of contact so we can disclose. Thank you

Kevin

### Reproduction steps

Private

### Screenshots

![DESCRIPTION](LINK.png)

### Logs

N/A

**Comment by JasonLandbridge** [comment]
Thanks for the suggestion, I have enabled it!

**Comment by JasonLandbridge** [comment]
Closing this now but I would be more than happy to hear about any vunnerabilities you might know about.
