### ISSUE TITLE
[BUG] wrong progress bar

### ISSUE THREAD

**Issue by bleriaf** [PlexRipper/PlexRipper#379]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

V0.23.2

### Platform

Unraid

### Browsers

Brave

### Description

Hello, there's a bug with plexripper; when downloading from a plex server especially series on some episodes it shows the percentage at 0% even tho the file was downloaded successfully
![image](https://github.com/user-attachments/assets/1dce8b6b-aee2-4d0b-ac5c-378735fb93f3)

these files were all downloaded succesfully and plexripper has even move on to downloading the next serie

**Comment by JasonLandbridge** [comment]
This has been fixed in the latest stable release!
