### ISSUE TITLE
[BUG] - No servers after configuring a user account on a fresh install v0.23.2

### ISSUE THREAD

**Issue by xmutantson** [PlexRipper/PlexRipper#380]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

V0.23.2

### Platform

Linux

### Browsers

Google Chrome

### Description

After configuring a user account, no servers populate. The account has 2 factor enabled, I have tried username and email logins.

### Reproduction steps

```bash
1. Go to 'Settings > Accounts, add account with "+"
2. Set 'Is Enabled', 'Is Main', display name, username, password, validate, enter two-factor code
3. Two-factor validated, click save
4. Refresh page, no servers appear
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
16:09:53 [Debug] [PlexApiWrapper.PlexSignInAsync:97] => Requesting PlexToken for account ***MASKED***

16:09:53 [Debug] [PlexApiClient.SendAsync:90] => Request: https://***MASKED***/api/v2/users/signin

16:10:02 [Warning] [PlexApiClient..ctor:59] => Request to https://***MASKED***/api/v2/users/signin failed, retrying 1 of 1 in 1s

16:10:10 [Debug] [PlexApiWrapper.PlexSignInAsync:97] => Requesting PlexToken for account ***MASKED***

16:10:10 [Debug] [PlexApiClient.SendAsync:90] => Request: https://***MASKED***/api/v2/users/signin

16:10:11 [Information] [PlexApiWrapper.PlexSignInAsync:142] => Successfully retrieved the PlexAccount data for user ***MASKED*** from the PlexApi

16:10:11 [Debug] [ValidatePlexAccountEndpoint.HandleAsync:79] => The PlexAccount with displayName ***MASKED*** has been validated

16:10:14 [Debug] [CreatePlexAccountEndpoint.HandleAsync:91] => Creating account with username xmutantson

16:10:14 [Debug] [RefreshPlexServerAccessCommand.Handle:52] => Refreshing Plex servers for PlexAccount: 2

16:10:14 [Information] [PlexApiService.GetPlexApiTokenAsync:290] => Plex AuthToken was still valid, using from local DB

16:10:14 [Debug] [PlexApiClient.SendAsync:90] => Request: https://***MASKED***/api/v2/resources

16:10:14 [Debug] [PlexApiClient.SendAsync:90] => Request: https://***MASKED***/api/v2/resources?includeHttps=1&includeRelay=1&includeIPv6=1

16:10:14 [Error] [ExceptionLoggingHandler.Handle:26] => An exception of type "System.ArgumentNullException" happened when handling request of type "PlexRipper.Application.RefreshPlexServerAccessCommand"

16:10:14 [Error] [ExceptionLoggingHandler.Handle:31] => Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetNonEnumeratedCount[TSource](IEnumerable`1 source, Int32& count)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at PlexRipper.PlexApi.PlexApiWrapper.GetAccessibleServers(String authToken) in /src/src/PlexApi/PlexApiWrapper.cs:line 252
   at PlexRipper.PlexApi.PlexApiService.GetAccessiblePlexServersAsync(Int32 plexAccountId) in /src/src/PlexApi/PlexApiService.cs:line 182
   at PlexRipper.Application.RefreshPlexServerAccessCommandHandler.Handle(RefreshPlexServerAccessCommand command, CancellationToken cancellationToken) in /src/src/Application/PlexServers/RefreshAccess/RefreshPlexServerAccessCommand.cs:line 54
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)

16:10:14 [Error] [CreatePlexAccountEndpoint.HandleAsync:118] => Failed to queue inspect server job for PlexAccount with id 2
```

**Comment by segmentturtle** [comment]
I'm also experiencing the same issue. I can log in eventually, but tells me no libraries found. Ever find a work around?

**Comment by joshhughes6** [comment]
Same here.  I actually had an account added and validated with libraries showing, but something got corrupted on the last docker update.  So I had to remove the image and re-install it.  Ever sense I get the same messages about no libraries found.  Is there a way to "roll back" from **latest** to the previous release?

Here is what I see in the logs:

07:30:25 [Error] [RefreshPlexServerAccessCommand.Handle:85] => Fluent Validation Pipeline Failed.
 - Metadata:
 -- StatusCode - 400
 - PlexServerConnections list cannot be empty.
 - PlexServerConnections list cannot be empty.

07:30:25 [Warning] [DbContextExtensions.PlexAccount.GetAccessiblePlexServers:91] => No accessible PlexServers found for PlexAccount: Josh

07:30:25 [Warning] [RefreshLibraryAccessCommand.Handle:62] => No accessible Plex servers found for PlexAccount Josh

**Comment by JasonLandbridge** [comment]
I'm currently wrapping up https://github.com/PlexRipper/PlexRipper/pull/384, after which I will work on this issue. Can someone send me an auth token to plexripper@protonmail.com, so I can investigate?

**Comment by JasonLandbridge** [comment]
@xmutantson and @Jgams Can you send me an auth token to [plexripper@protonmail.com](mailto:plexripper@protonmail.com), so I can investigate? 

It seems the latest version on the `:dev` image has fixed it for @joshhughes6 so I'm closing this now but let me know if this is still an issue for you guys.
