### ISSUE TITLE
[BUG] - Issues starting on Raspberry Pi 5 Model B Rev 1.0

### ISSUE THREAD

**Issue by Llntrvr** [PlexRipper/PlexRipper#383]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

v0.24.0

### Platform

Linux

### Browsers

Google Chrome

### Description

Try to start up the docker container and getting back

**plexripper exec /init exec format error**

**docker.yaml**
`---
services:
  plexripper:
    image: plexripper/plexripper
    container_name: plexripper
    environment:
      - PUID=1001
      - PGID=100
      - TZ=America/Los_Angeles
      - UNMASKED=false # Unmask sensitive data in logs if true
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/plexripper/config:/Config:rw
      - /srv/mergerfs/media/media/downloads/plexripper:/Downloads:rw
      - /srv/mergerfs/media/media/movies:/Movies:rw
      - /srv/mergerfs/media/media/tvshows:/TvShows:rw    
    ports:
      - 7000:7000
    restart: unless-stopped
`

**System Info:**
Processor
Raspberry Pi 5 Model B Rev 1.0

Kernel
Linux 6.6.51+rpt-rpi-2712

### Reproduction steps

```bash
Use aboue Info
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
plexripper exec /init exec format error
```

**Comment by JasonLandbridge** [comment]
Closing because duplicate: https://github.com/PlexRipper/PlexRipper/issues/363
