### ISSUE TITLE
Downloads not Starting

### ISSUE THREAD

**Issue by jb123567** [PlexRipper/PlexRipper#390]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

0.25

### Platform

Unraid

### Browsers

Google Chrome

### Description

2 issues with the install, I think they are probably user error.

I can’t seem to download an individual TV programme, I can download the whole directory, but when I use the selection tool I can’t trigger a download, it just doesn’t prompt me to proceed.

I also can’t seem to download anything from a Remote server with the errors below -

### Reproduction steps

```bash
Download from remote server.

Try and download something using selection tool.
```

### Logs

```bash
20:53:12 - Sunday, 24 November 2024
20:53:12 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:302] => Download worker with id: 23 and with filename: Alice in Wonderland (2010).part3.mkv changed status to "Error"
20:53:12 - Sunday, 24 November 2024
20:53:12 [Error] [DownloadWorker.SetDownloadWorkerTaskChanged:319] => Download worker 23 with Alice in Wonderland (2010).part3.mkv had an error!
20:53:12 - Sunday, 24 November 2024
20:53:12 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:302] => Download worker with id: 21 and with filename: Alice in Wonderland (2010).part1.mkv changed status to "Error"
20:53:12 - Sunday, 24 November 2024
Result: IsSuccess='False', Reasons='Error with Message=' 20:53:12 [Error] [DownloadWorker.DownloadProcessAsync:198] => Download worker 23 with Alice in Wonderland (2010).part3.mkv had an empty download stream ', Metadata='[DownloadWorkerId, 23]''
20:53:12 - Sunday, 24 November 2024
20:53:12 [Error] [DownloadWorker.SetDownloadWorkerTaskChanged:319] => Download worker 21 with Alice in Wonderland (2010).part1.mkv had an error!
20:53:12 - Sunday, 24 November 2024
Result: IsSuccess='False', Reasons='Error with Message=' 20:53:12 [Error] [DownloadWorker.DownloadProcessAsync:198] => Download worker 21 with Alice in Wonderland (2010).part1.mkv had an empty download stream ', Metadata='[DownloadWorkerId, 21]''
20:53:12 - Sunday, 24 November 2024
20:53:12 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:302] => Download worker with id: 22 and with filename: Alice in Wonderland (2010).part2.mkv changed status to "Error"
20:53:12 - Sunday, 24 November 2024
20:53:12 [Error] [DownloadWorker.SetDownloadWorkerTaskChanged:319] => Download worker 22 with Alice in Wonderland (2010).part2.mkv had an error!
20:53:12 - Sunday, 24 November 2024
Result: IsSuccess='False', Reasons='Error with Message=' 20:53:12 [Error] [DownloadWorker.DownloadProcessAsync:198] => Download worker 22 with Alice in Wonderland (2010).part2.mkv had an empty download stream ', Metadata='[DownloadWorkerId, 22]''
20:53:12 - Sunday, 24 November 2024
20:53:12 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:302] => Download worker with id: 24 and with filename: Alice in Wonderland (2010).part4.mkv changed status to "Error"
20:53:12 - Sunday, 24 November 2024
20:53:12 [Error] [DownloadWorker.SetDownloadWorkerTaskChanged:319] => Download worker 24 with Alice in Wonderland (2010).part4.mkv had an error!
20:53:12 - Sunday, 24 November 2024
Result: IsSuccess='False', Reasons='Error with Message=' 20:53:12 [Error] [DownloadWorker.DownloadProcessAsync:198] => Download worker 24 with Alice in Wonderland (2010).part4.mkv had an empty download stream ', Metadata='[DownloadWorkerId, 24]''
```

**Comment by JasonLandbridge** [comment]
Hi, can you verify that the folder paths are valid and writable in the settings?

**Comment by jb123567** [comment]
> Hi, can you verify that the folder paths are valid and writable in the settings?

I can download from the local server, I assume that wouldn't work if they weren't? The server is set to write straight into the Plex directory and is running as Root.

**Comment by ghost** [comment]
same issue - well i don't have the right for download - only for watching movies from remote plex instance.

for some reason I had yesterday some downloads witch did start but didn't finish ... they were aborted about 10 to 11 minutes after start. (maybe there is some time-based token which isn't renewed? - idk just a guess)

today none of the downloads did start ...   

permission to write are ok - the folders an part-files were created
used platform: docker/linux

**Comment by ghost** [comment]
had some more tries - now a download started, but was aborted after 10 minutes

**Comment by jb123567** [comment]
> had some more tries - now a download started, but was aborted after 10 minutes

If you try and download a single episode of a TV programme do you even get the dialogue box to start a download?

**Comment by ghost** [comment]
no , when trying to download a single episode   the download box doesn't appear. 
it's only  possible to select a whole tv-show. I'm using firefox 132.0.1 (64-Bit) / fedora.

(addendum: the download started, when i started watching the movie at the same time - maybe the initial request took too long, when the movie-file on the server was "cold")

**Comment by JasonLandbridge** [comment]
Thanks for the report! 

2 issues I have concluded from you both:
 - The selection of media doesn't trigger the download confirmation or actual downloads 
    - This is now fixed: #391, not yet released though
 - Download fails/aborts after a set amount of time
    - I could not replicate this error, I have managed to download everything fine from a remote server, tv-shows and movies

Can either of you who have issue 2 send a Plex token to plexripper@protonmail.com with the exact Plex server, Plex Library and media item you're attempting to download so I can replicate the error?

**Comment by JasonLandbridge** [comment]
Release https://github.com/PlexRipper/PlexRipper/releases/tag/v0.26.0 fixes issue 1

**Comment by jb123567** [comment]
I can confirm I can now that issue 1 is resolved.

**Comment by jb123567** [comment]
So I have worked out the issue, the remote server had an upload limit restriction on it, with this enabled the stream just would not work.

**Comment by ghost** [comment]
Maybe the log will help you for the beginning...
```

20:41:16 [Debug] [GenerateDownloadTaskMoviesCommand.Handle:44] => Creating 1 movie download tasks

20:41:16 [Information] [DownloadQueue.CheckDownloadQueue:44] => Adding 1 PlexServers to the DownloadQueue to check for the next download

20:41:16 [Debug] [DownloadQueue.CheckDownloadQueueServer:75] => Checking PlexServer: ***MASKED*** for the next download to start

20:41:16 [Information] [DownloadQueue.CheckDownloadQueueServer:93] => Selected download task Vaiana (2016)/Vaiana (2016).mkv to start as the next task

20:41:16 [Debug] [DownloadJob.Execute:45] => Executing job: DownloadJob for downloadTaskKey with id: MovieData Id: a47dc60e-0212-4316-bedc-1c22d6576132, Server: 3, Library: 25

20:41:16 [Debug] [DownloadJob.Execute:93] => Generated DownloadWorkerTasks for Vaiana (2016)/Vaiana (2016).mkv

20:41:16 [Debug] [DownloadJob.Execute:98] => Creating Download client for Vaiana (2016)/Vaiana (2016).mkv

20:41:16 [Debug] [PlexDownloadClient.Start:130] => Start downloading Vaiana (2016).mkv

20:41:16 [Debug] [DownloadWorker.Start:102] => Download worker with id: 199 start for filename: Vaiana (2016).part1.mkv

20:41:16 [Debug] [PlexApiClient.SendAsync:89] => Request: https://***MASKED***/library/parts/1671255/1567608565/file.mkv?X-Plex-Token=***MASKED***

20:41:16 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:302] => Download worker with id: 199 and with filename: Vaiana (2016).part1.mkv changed status to Downloading

20:41:16 [Debug] [PlexDownloadClient.OnDownloadWorkerTaskUpdate:197] => DownloadTaskUpdate: [MovieData] [Downloading] [Vaiana (2016).mkv] [Download Location: /Downloads/Movies/Vaiana]

20:41:17 [Debug] [PlexDownloadClient.OnDownloadWorkerTaskUpdate:197] => DownloadTaskUpdate: [MovieData] [Downloading] [Vaiana (2016).mkv] [Download Location: /Downloads/Movies/Vaiana]


[...]

20:51:33 [Debug] [PlexDownloadClient.OnDownloadWorkerTaskUpdate:197] => DownloadTaskUpdate: [MovieData] [Downloading] [Vaiana (2016).mkv] [Download Location: /Downloads/Movies/Vaiana]

20:51:34 [Warning] [DownloadWorker..ctor:71] => Retry 1 due to {exception.Message}. Retrying in {timeSpan.TotalSeconds}s.

20:51:34 [Debug] [PlexDownloadClient.OnDownloadWorkerTaskUpdate:197] => DownloadTaskUpdate: [MovieData] [Downloading] [Vaiana (2016).mkv] [Download Location: /Downloads/Movies/Vaiana]

20:51:36 [Warning] [DownloadWorker..ctor:71] => Retry 2 due to {exception.Message}. Retrying in {timeSpan.TotalSeconds}s.

20:51:40 [Warning] [DownloadWorker..ctor:71] => Retry 3 due to {exception.Message}. Retrying in {timeSpan.TotalSeconds}s.

20:51:43 [Debug] [PlexApiClient.SendAsync:89] => Request: http://***MASKED***/identity

20:51:43 [Debug] [PlexApiClient.SendAsync:89] => Request: http://***MASKED***/identity

20:51:43 [Debug] [PlexApiClient.SendAsync:89] => Request: https://***MASKED***/identity

20:51:43 [Debug] [PlexApiClient.SendAsync:89] => Request: https://***MASKED***/identity

20:51:48 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:302] => Download worker with id: 199 and with filename: Vaiana (2016).part1.mkv changed status to Error

20:51:48 [Error] [DownloadWorker.SetDownloadWorkerTaskChanged:319] => Download worker 199 with Vaiana (2016).part1.mkv had an error!

20:51:48 [Debug] [PlexDownloadClient.OnDownloadWorkerTaskUpdate:197] => DownloadTaskUpdate: [MovieData] [Error] [Vaiana (2016).mkv] [Download Location: /Downloads/Movies/Vaiana]

20:51:48 [Debug] [DownloadJob.Execute:137] => Exiting job: DownloadJob for DownloadTaskGeneric with id: MovieData Id: a47dc60e-0212-4316-bedc-1c22d6576132, Server: 3, Library: 25

20:51:48 [Warning] [DownloadJob.Dispose:148] => Disposing job: DownloadJob for DownloadTaskGeneric

20:51:48 [Warning] [PlexDownloadClient.DisposeAsync:176] => PlexDownloadClient for DownloadTask with Id: a47dc60e-0212-4316-bedc-1c22d6576132 was disposed

```

**Comment by ghost** [comment]
`
22:03:04 - Tuesday, 26 November 2024
Result: IsSuccess='False', Reasons='ExceptionalError with Message='The response ended prematurely, with at least 2622453069 additional bytes expected. (ResponseEnded)', Metadata='[DownloadWorkerId, 201]', Exception='System.Net.Http.HttpIOException: The response ended prematurely, with at least 2622453069 additional bytes expected. (ResponseEnded) at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) at PlexRipper.Domain.ThrottledStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /src/src/Domain/Common/FileSystem/ThrottledStream.cs:line 80 at PlexRipper.Application.DownloadWorker.<>c__DisplayClass28_0.<<DownloadProcessAsync>b__0>d.MoveNext() in /src/src/Application/PlexDownloads/Execute/DownloadClient/DownloadWorker.cs:line 205 --- End of stack trace from previous location --- at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext) at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext) at PlexRipper.Application.DownloadWorker.DownloadProcessAsync(CancellationToken cancellationToken) in /src/src/Application/PlexDownloads/Execute/DownloadClient/DownloadWorker.cs:line 187''
`

**Comment by JasonLandbridge** [comment]
@temberjosef Your issue seems to be separate from the initial issue here, as in I don't know why it's happening to you without seeing it for myself. 

There is an issue where your log is not displaying the actual error, so I will fix that.

Again, please send a Plex token to [plexripper@protonmail.com](mailto:plexripper@protonmail.com) with the exact Plex server, Plex Library and media item you're attempting to download, and then I can replicate the error.

**Comment by JasonLandbridge** [comment]
#396 Is available on the dev channel and should fix the above
