### ISSUE TITLE
Deploying a new setup button do not work

### ISSUE THREAD

**Issue by jmakepeace** [PlexRipper/PlexRipper#57]
When you create a new setup and try to click the buttons they do not do anything but an error is shown in the browser console 

TypeError: Cannot read properties of undefined (reading 'replace')

once you have gone past the initial setup stage then clicking the options in the left menu like paths, ui, advanced this does not do anything apart from change the path nothing is displayed in the right hand pane

**Comment by JasonLandbridge** [comment]
Hey, thanks for pointing this out! I will continue working on PlexRipper this next weekend and will fix this. Are you on the Master or Dev image?

**Comment by jmakepeace** [comment]
Have tried dev and master both give the same result

**Comment by JasonLandbridge** [comment]
Hey @jmakepeace, I have been working this past weekend and made several fixes. I have also been able to reproduce the issue you are talking about and I am currently fixing that as well.

I will let you know once I have a fixed version available!

**Comment by PlexRipper** [comment]
This should be fixed as well, test it on the dev image please!
