### ISSUE TITLE
auth plex w/ cloudflare tunnel option

### ISSUE THREAD

**Issue by rodrigorodrigo** [PlexRipper/PlexRipper#69]
I don't know how much work it is, but as my plex is under cloudflare (using cloudflared package for tunneling) and so it cannot connect directly to the public IP. Any way to get around that?

EDIT: perhaps via URL would work?

**Comment by JasonLandbridge** [comment]
Hey, 

So what I understand, your Plex Media Server is hosted on Cloudflare and PlexRipper cannot connect or retrieve data from it? A Plex Media Server has to be [remotely accessible](https://support.plex.tv/articles/200289506-remote-access/) from where PlexRipper is running to call its API. 

It could be possible to manually enter a URL and token for PlexRipper to then connect to the server, is that what you're asking?

Also, which Cloudflare package are you using? And you have any more info I can use?

**Comment by rodrigorodrigo** [comment]
Yes, I believe that would do the trick. The container I am using to do the Argo tunneling is https://github.com/aeleos/cloudflared. I have plex remote access both from my domain and from Plex website so my server is reachable.
The way I set the tunnel up (and I guess some other unraid folks did so too) is documented here https://docs.ibracorp.io/all-guides-in-order/documentation/cloudflare-tunnel.

**Comment by JasonLandbridge** [comment]
Good to hear that you got it fixed! I will take a look at Overseerr and see how they are connecting. Hopefully I can integrate their methods in PlexRipper as well! Thanks for sharing the info!
