### ISSUE TITLE
[Translation] - French PlexRipper Translation

### ISSUE THREAD

**Issue by starnakin** [PlexRipper/PlexRipper#70]
I want made the french translation but I can't find the Lang folder like in the readme

**Comment by JasonLandbridge** [comment]
Thank you very much for that! I indeed see the broken link, just give me a bit of time and I will add a French language file which you can translate. I also have some strings I still need to add there so I will go through those as well

**Comment by JasonLandbridge** [comment]
Hey, I have added all the missing translations to the [lang](https://github.com/PlexRipper/PlexRipper/tree/master/src/WebAPI/ClientApp/src/lang) folder. In there you will also find a `fr-FR.json` language file for French, which if translated can be used directly in PlexRipper as it now has a language option. I would say 90-95% of all text is in there.

I would also highly recommend you use something like [i18n Manager](https://github.com/gilmarsquinelato/i18n-manager) to translate everything.

Thanks again and let me know if you have any questions!

**Comment by starnakin** [comment]
This is the first version if necessary I can retranslate some terms to make it better but not today, today I need to sleep xD
[French.zip](https://github.com/PlexRipper/PlexRipper/files/7246763/French.zip)

**Comment by JasonLandbridge** [comment]
Vous légende absolue! (You absolute legend!)
Thank you so much! It worked instantly and I will include it in the next release!
I noticed I forgot some translations to include so I used google translate, let me know if I got anything wrong:


![image](https://user-images.githubusercontent.com/15127381/135173312-adde7d28-f4c0-4c6e-a68c-cb496034105f.png)

And:
"This might take around 5 minutes or longer and then this window will close on its own!"
=>
"Cela peut prendre environ 5 minutes ou plus, puis cette fenêtre se fermera d'elle-même!

I also noticed that French is quite a bit more text so I will need to fix some UI to account for this:
![image](https://user-images.githubusercontent.com/15127381/135174317-63e6fbfd-7256-4a73-b342-9f217e549ffc.png)

Can I add your username @starnakin or any other name to the contributions in the ReadMe?

Thanksn again!

**Comment by starnakin** [comment]
Wow this is incredible (this project can be very very insane), I think my translation is actually not perfect but It is the first version, if I have the time this night I gonna make a second version (because I see some grammatical error) . And for my name in the readme, if it is possible I want !

**Comment by JasonLandbridge** [comment]
Thanks! Yeah I have been working on this for the past 1.5 years and I still see so many awesome things I can do with it! 

I have added your contribution:
![image](https://user-images.githubusercontent.com/63810118/135238175-acc2e03e-1775-44bb-9a46-c893b7d40b2b.png)

The new translation and your contribution are not yet visible, I first need to merge it which I hope to do tonight with some other fixes.

Temp link to the lang folder: https://github.com/PlexRipper/PlexRipper/tree/FixingAccountProgress/src/WebAPI/ClientApp/src/lang

**Comment by JasonLandbridge** [comment]
I have created a new release with the French translation, its currently on the development branch:
https://github.com/PlexRipper/PlexRipper/releases/tag/v0.8.7

**Comment by JasonLandbridge** [comment]
I have created a discussion here https://github.com/PlexRipper/PlexRipper/discussions/165, please continue the discussion there so I can close this issue to clean things up
