### ISSUE TITLE
TOOLTIPS

### ISSUE THREAD

**Issue by alaska4life** [PlexRipper/PlexRipper#71]
Tooltips when you hover over icons would be a big help.  For instance, on the downloads tab, I have some downloads going and there is an icon that has three vertical bars in a box, and I want to click it, but I don't want it to cancel the downloads.  I feel like its a status icon, but, not sure.  Hence, tooltips when you hover and icon would be nice.

**Comment by JasonLandbridge** [comment]
Yes I see what you mean, will add those as well! Some features are not too clear so I will either add some tooltips and/or help pages around PlexRipper

**Comment by JasonLandbridge** [comment]
This is a more generic enhancement that is being implemented as I go so I will close it for now
