### ISSUE TITLE
CAN'T SORT MOVIES IN LIBRARY OR DOWNLOADS

### ISSUE THREAD

**Issue by alaska4life** [PlexRipper/PlexRipper#72]
It would be nice if you can sort the columns by clicking on the columns.  Like title, year, size, etc.  Would be helpful to be able to sort.

**Comment by JasonLandbridge** [comment]
Yes! This is a smaller feature which I hope to have implemented soon!

**Comment by JasonLandbridge** [comment]
Closing this as it's a duplicate of #93
