### ISSUE TITLE
[Feature] - 2FA Plex account compatibility in PlexRipper

### ISSUE THREAD

**Issue by BigFam194** [PlexRipper/PlexRipper#74]
When adding an account with 2FA enabled the guide throws an error and the account can't be added

**Comment by JasonLandbridge** [comment]
Thanks for reporting! Someone else mentioned this as well: [Unraid Forum Post](https://forums.unraid.net/topic/114103-support-plexripper-the-best-cross-platform-plex-media-downloader-there-is/?do=findComment&comment=1038831)

For now, removing 2FA works as a solution but it is definitely on my to-do list of things to fix. I will keep you posted!

**Comment by BigFam194** [comment]
Exciting work on your project 👍🏻

mån 27 sep. 2021 kl. 20:55 skrev JasonLandbridge ***@***.***>:

**Comment by fizzyfrys** [comment]
Also having the same issue, hoping for an update that supports 2FA

**Comment by JasonLandbridge** [comment]
I have created a new release which supported 2FA Plex Accounts with many more fixes, its currently on the development branch:
https://github.com/PlexRipper/PlexRipper/releases/tag/v0.8.7

I did assume you will have an phone app that generates a 6 digit number, this can now be entered when setting up your account. 

Please let me know if this fixes your issue

**Comment by BigFam194** [comment]
Awesome, thanks!
I'll give it a try tomorrow!

sön 3 okt. 2021 kl. 17:58 skrev JasonLandbridge ***@***.***>:
