### ISSUE TITLE
Option to limit download speed

### ISSUE THREAD

**Issue by abra1c** [PlexRipper/PlexRipper#77]
My friends hates it when I suck all of their juicy upload speed.

**Comment by JasonLandbridge** [comment]
Thanks for the feedback, ironically I have this feature already implemented for testing purposes but I will expose this option in the front-end as well. Hopefully in the next update after the one that is coming today!

**Comment by jmmille** [comment]
Is there currently a speed limiter built into v0.8.6?  I'm seeing about 3MB/s with the tool, but if I click on the Download URL, it downloads at about 40MB/s, which is the speed of my internet.

**Comment by JasonLandbridge** [comment]
This has been implemented in the latest v0.9.0! Closing now
