### ISSUE TITLE
Error: Not enough space available

### ISSUE THREAD

**Issue by abra1c** [PlexRipper/PlexRipper#79]
I just updated to the latest non development version on Unraid. Downloads are broken with a not enough disk space available error in the log. There is clearly enough space and I can copy other, much larger files to that directory too.

**Comment by JasonLandbridge** [comment]
Hey, can you send me some of the logs so I can see what's wrong. If there is sensitive information in there then please send it to [PlexRipper@protonmail.com](PlexRipper@protonmail.com)

**Comment by abra1c** [comment]
Hi, now I had time to reproduce the error. Here are my logs.
I censored everything that I am not willing to share
[log20211006.txt](https://github.com/PlexRipper/PlexRipper/files/7295463/log20211006.txt)
.

**Comment by abra1c** [comment]
I have found the issue. The problem only seems to happen when I reduce the download segments size to lower than 4.

**Comment by JasonLandbridge** [comment]
I'm quite sure this has been fixed in the latest v0.9.0 release, please re-open if you still have this problem
