### ISSUE TITLE
[Bug] - MediaOverview can't find correct PlexLibraryId and gets stuck in loading

### ISSUE THREAD

**Issue by projdarkmoon** [PlexRipper/PlexRipper#81]
Hello, When i open a remote library im able to browse the movie related items, but when i goto TV shows it just sticks at loading at 0%, i thought it would be maybe its just building, but having it up for an hour does nothing (Happens on both regular and developmental releases) Screenshot attached
![image](https://user-images.githubusercontent.com/14205729/135562447-d9200cdc-32fc-4e2c-8454-7621c9182822.png)

**Comment by JasonLandbridge** [comment]
Thanks for this, could you show the console errors? Press F12 if you have chrome and make a screenshot of the console there

**Comment by projdarkmoon** [comment]
![image](https://user-images.githubusercontent.com/14205729/135610359-649072d3-dc7d-4597-ac12-b014c75e3cc0.png)
none

**Comment by JasonLandbridge** [comment]
Okay no problem, I think I have come across this as well so I can replicate it and fix it

**Comment by projdarkmoon** [comment]
Also to Add.... i noticed under Network section when i go to TV Show related items i see this kick back: http://xxx.xxx.xxx.xxx:7001/api/plexLibrary/NaN?plexAccountId=0 Not sure if this helps (the xxx.xxx.xxx.xxx is the server local ip)

**Comment by JasonLandbridge** [comment]
Ah that's a great clue! Then it can't find the PlexLibraryId, thanks!

**Comment by JasonLandbridge** [comment]
Thanks to your helpful report I have been able to fix this! It's in the new release with many other fixes, its currently on the development branch:
https://github.com/PlexRipper/PlexRipper/releases/tag/v0.8.7

**Comment by projdarkmoon** [comment]
Glad i could help, I am able to see the TVShow related Library now. Lets do some testing with downloading. Ill let you know how it goes.

**Comment by projdarkmoon** [comment]
Works fine! Thanks again
