### ISSUE TITLE
Does not appear to be able to connect to plex servers behind reverse proxies

### ISSUE THREAD

**Issue by Rhainland** [PlexRipper/PlexRipper#82]
When adding a server thats behind a reverse proxy, plexripper indicate it cant create SSL handshake, it then attempts to add a DNS entry for some IP:443, which also fails.

E.g if the plex server is behind an nginx reverse proxy and remote access is disabled, thus the server exposes itself via plex on https://somerandomdomain.com - Plexripper is unable to connect

If i in plexripper DB change the following values;
PlexServers
 address -> https://somedomain.com
 host -> somedomain.com

Then go to UI, pick the server and click "check server status" then plexripper indicate it successfully connects;
 Request to https://somedomain/identity?X-Plex-Token=TOKEN was successful!

However since the server wasnt added through the "normal" process in plexripper, no libraries are detected or shown.

**Comment by JasonLandbridge** [comment]
Thank you very much for this! Auto detecting this might be a bit difficult in the short term but I could add an option to manually add a reverse proxy domain to a server and then PlexRipper will use that to establish a connection. 

On your last point, you can refresh accessible servers and libraries by going here:

![image](https://user-images.githubusercontent.com/15127381/135760048-a0be2dd8-8c4d-4946-b5cd-b7d05ee80988.png)

Not sure if it works but otherwise I will fix it in a near update.

**Comment by Rhainland** [comment]
> Thank you very much for this! Auto detecting this might be a bit difficult in the short term but I could add an option to manually add a reverse proxy domain to a server and then PlexRipper will use that to establish a connection.
> 
> On your last point, you can refresh accessible servers and libraries by going here:
> 
> ![image](https://user-images.githubusercontent.com/15127381/135760048-a0be2dd8-8c4d-4946-b5cd-b7d05ee80988.png)
> 
> Not sure if it works but otherwise I will fix it in a near update.

Thanks for your reply!. 

Unfortunately refreshing doesnt work, that attempts to establish connection similar to first time you add the server, meaning it will replace the reverse proxy url that i manually added via db, with the attempted DNS fix(in this case ip:443 which will fail)

And so it just breaks the entire connection trying to do that.

Looking forward to your fix in the future, im excited to try this application out!

**Comment by JasonLandbridge** [comment]
No problem, any chance this server happens to be your own and you could invite me for testing a fix? I will have a dummy account which you can kick off after I have fixed this issue. No problem if you would rather not.

**Comment by Rhainland** [comment]
> No problem, any chance this server happens to be your own and you could invite me for testing a fix? I will have a dummy account which you can kick off after I have fixed this issue. No problem if you would rather not.

It is not my own, so i cannot invite :(

**Comment by JasonLandbridge** [comment]
Okay no problem, this might sound a bit petty but I don't mean it like that at all. But I do need a server which has this configured to find and test a fix. I can maybe set one up myself, but that takes, I'm afraid, quite a bit of time. So I will keep my eyes open and I might be able to find a similar one. 

If this server happens to be open for registration then please send an e-mail to PlexRipper@protonmail.com with details on this server. Then I can request access as well and investigate that way. 

Thanks!

**Comment by Rhainland** [comment]
> Okay no problem, this might sound a bit petty but I don't mean it like that at all. But I do need a server which has this configured to find and test a fix. I can maybe set one up myself, but that takes, I'm afraid, quite a bit of time. So I will keep my eyes open and I might be able to find a similar one.
> 
> If this server happens to be open for registration then please send an e-mail to [PlexRipper@protonmail.com](mailto:PlexRipper@protonmail.com) with details on this server. Then I can request access as well and investigate that way.
> 
> Thanks!

I have sent an invite to PlexRipper@protonmail.com now to a server thats behidn a reverse proxy

**Comment by JasonLandbridge** [comment]
Thank you very much! I am currently rewriting the download process code and resolving several issues with that. I hope with this I can also resolve the reverse proxy. If all goes well I should have a new update by the end of this week!

**Comment by Rhainland** [comment]
Thanks! Looking forward to it!

**Comment by JasonLandbridge** [comment]
Okay that took way longer that I would have liked, this might be related to #108 , I will fix that one first and then check if that also solves the reverse proxy issue

**Comment by JasonLandbridge** [comment]
I think I have finally fixed this issue, with the new release you can now select which connection you would like to use in the server settings. This connection will then always be used when downloading.

A new release ([0.10.0-RC-1](https://github.com/PlexRipper/PlexRipper/releases/tag/v0.10.0-RC1)) is available now on both the [latest](https://hub.docker.com/r/plexripper/plexripper/tags) and [dev](https://hub.docker.com/r/plexripper/plexripper/tags) docker channels, which contains all the changes/fixes from the past several months. Let me know if this fixes the issues.
