### ISSUE TITLE
[Bug] - Slow download speeds compared to direct downloads

### ISSUE THREAD

**Issue by JasonLandbridge** [PlexRipper/PlexRipper#85]
It has been reported several times that certain servers have a much slower download speed when using PlexRipper, compared to direct downloading through a browser. I have been able to reproduce this so I will investigate this, I hope to have a fix in the next release as this is a high priority one. 

![image](https://user-images.githubusercontent.com/15127381/135762804-e4e01a1c-1043-4126-9885-d33d4eb9b4ac.png)

**Workaround:**

Downloading something will show a "graph icon" next to it on the download page. Click it and it will open some details which include a direct download link:

![image](https://user-images.githubusercontent.com/15127381/135763061-e41435d9-7fe8-4cb1-8506-1fbb48fa4d21.png)

**Comment by imTHAI** [comment]
I have the same problem

**Comment by EricLauber** [comment]
@JasonLandbridge I have found that the link you are indicating here hasn't worked for me. I had to make a change and add a query parameter.

Instead of
`http://SERVER:PORT/KEY?X-Plex-Token=TOKEN`, I had to use `http://SERVER:PORT/KEY?download=1&X-Plex-Token=TOKEN`.

**Comment by BakasuraRCE** [comment]
Hey @JasonLandbridge this is a buffer problem, check this:
https://stackoverflow.com/questions/39353119/filestream-readasync-very-slow-compared-to-read

I Just the 4096 by 524288000(500 MB) and disabled the throttledStream, done! full speed
https://github.com/PlexRipper/PlexRipper/blob/7ac74e9e8c3b84aececfd138b0d42baabc627856/src/DownloadManager/Download/DownloadWorker.cs#L217

**Comment by JasonLandbridge** [comment]
@BakasuraRCE thank you so much! This was indeed the issue and I have been able to fix this in the latest v0.9.0 release. I've given you an honorable mention in the [release notes](https://github.com/PlexRipper/PlexRipper/releases/tag/v0.9.0)

**Comment by BakasuraRCE** [comment]
With pleasure, always willing to help :)
