### ISSUE TITLE
[Bug] - Incorrect file permissions are given to finished downloads

### ISSUE THREAD

**Issue by JasonLandbridge** [PlexRipper/PlexRipper#87]
Example: "When your container brings the file in to my media folder for instance /plex/movies (does the same for tv.) it turns it in to root access only. Only the root member can make changes to this file. Only way to fix this is to run unraid's new permissions."

**Comment by zbejas** [comment]
I also have the same issue.

**Comment by JasonLandbridge** [comment]
I think I might have fixed this in the latest v0.9.0 release but I need a confirmation for this one. I added PID and GID to the unraid template but I'm not sure if this has fixed it.

**Comment by Animizio** [comment]
for the docker version its not fixed yet

**Comment by ChronoStriker1** [comment]
Confirming this is still not working as intended.

**Comment by JasonLandbridge** [comment]
This is unfortunately part of a larger issue which I need help with, see this for more info: https://github.com/PlexRipper/PlexRipper/issues/208
