### ISSUE TITLE
[Translation] - Korean PlexRipper Translation

### ISSUE THREAD

**Issue by pparkjyy** [PlexRipper/PlexRipper#92]
Hello , I loved your work and would like to add Korean translation . is it okay?

**Comment by pparkjyy** [comment]
thanks for your permission, I'll work on it as soon as possible!

**Comment by pparkjyy** [comment]
Hi, please check your email!

**Comment by JasonLandbridge** [comment]
Awesome! Thank you very much @pparkjyy! I will include it as soon as possible!
