### ISSUE TITLE
sort the list or decide which values to see

### ISSUE THREAD

**Issue by DiniMuetter85** [PlexRipper/PlexRipper#93]
Hello
1. I saw already that someone requested the function to sort by name, year, size, etc...
would it be also possible to add a function that a user can decide which value they want to see.
for example:
show me only name and year, and hide size, added date, updated date.

2. Add IMDB-ID for movies
3. Add TBDV-ID for Series
4. Add the function to export the list as excel or *.txt file.

**Comment by JasonLandbridge** [comment]
Thanks for the ideas! 1, 2 and 3 is something I would like to do as well but I first need a general search bar implemented with all the functionality that come with it before I can do things like advanced filtering. This is planned for release v.0.10

And what would 4 be for? As a back-up of all the media listed in a library?

**Comment by DiniMuetter85** [comment]
Nr. 4 would be used to extract the conent list of another server and then feed that list in to Sonarr or Radarr to compair if there is any serie or movie in there library which is missing in my Sonarr or Radarr.
Instead of "stealing" the content itself from another Plex Server, nr. 4 would give me the posibility to extract the conent in a list format which then can be importet to the specific *ARR instance and i can download the missing stuff from my Usenet Indexer or Torrent Trackers.

**Comment by JasonLandbridge** [comment]
Ah I see, do you have a specific format in mind? Like the order of the data in columns, what kind of data etc?

**Comment by DiniMuetter85** [comment]
> Ah I see, do you have a specific format in mind? Like the order of the data in columns, what kind of data etc?

https://github.com/sirk123au/ArrTools
I would like to use this tool here.

**Comment by JasonLandbridge** [comment]
Yeah that sounds cool, I will put it on the feature list! Thanks for the suggestion

**Comment by JasonLandbridge** [comment]
Closing this in favor of https://github.com/PlexRipper/PlexRipper/issues/277
