### ISSUE TITLE
Unable to download via the interface

### ISSUE THREAD

**Issue by GoBooth** [PlexRipper/PlexRipper#94]
Very cool concept!

I tried several times to download a movie from my Friend's plex server. 
This friend has Fiber internet (1GB up/down) i thought it was weird that the movie was only downloading at around 2kb/s.
The download eventually errored out.
I refreshed everything and restarted the download.. it seems to stay stuck in "initialize" for a little bit but eventually starts, but still very slow.

However, to my surprise, when I clicked on the details icon next to the movie (under actions) it shows me the download URL along with a button to click. With this. I was able to download the entire 8Gb file in about 30 seconds.

So it seems that it can work, but via the GUI there's something wrong.
my first thought was the destination folders, but I double-checked them and they seem right.
Where are the logs for this app? I'm sure I can find useful information there.

**Comment by JasonLandbridge** [comment]
Yes this has been confirmed to be fixed in the latest v0.9.0 release!
