### ISSUE TITLE
Error Synching/Refreshing huge Libraries - Internal Server Error 500

### ISSUE THREAD

**Issue by jimbo19922003** [PlexRipper/PlexRipper#95]
Large libraries do not appear to refresh or become visible. Several smaller libraries on the same server work but the primary libraries seem to be timing out from reviewing the logs. This results in an internal server error popup message on failure.

I tried to manually synch from the server commands menu and was receiving the same error. 

LOGS:
20:14:45 [Debug] [PlexApiClient.GenerateResult] => Request to http://X:12400/library/sections?X-Plex-Token=TOKEN (OK) was successful!: 

20:14:46 [Debug] [PlexApiClient.GenerateResult] => Ok successful: 

20:14:46 [Debug] [PlexApiClient.GenerateResult] => StatusCode - 200: 

20:14:46 [Debug] [PlexApiClient.GenerateResult] => Request to http://X:12400/library/sections/7/all?X-Plex-Token=TOKEN (OK) was successful!: 

20:14:50 [Debug] [CreateUpdateOrDeletePlexMoviesCommandHandler.Handle] => Starting adding or updating movies in library: 4K Movies DolbyVision

20:14:52 [Debug] [PlexApi.GetLibrarySectionsAsync] => GetLibrarySectionsAsync => http://X:12400/library/sections

20:14:52 [Debug] [PlexApiClient.GenerateResult] => Ok successful: 

20:14:52 [Debug] [PlexApiClient.GenerateResult] => StatusCode - 200: 

20:14:52 [Debug] [PlexApiClient.GenerateResult] => Request to http://X:12400/library/sections?X-Plex-Token=TOKEN (OK) was successful!: 

20:15:02 [Warning] [PlexApiClient.SendRequestAsync] => Waiting 1 seconds before retrying again.

20:15:02 [Error] [PlexApiClient.SendRequestAsync] => Error Response URI:  - (0)

20:15:02 [Error] [PlexApiClient.SendRequestAsync] => Error Message: The request timed-out.

20:15:13 [Warning] [PlexApiClient.SendRequestAsync] => Waiting 2 seconds before retrying again.

20:15:13 [Error] [PlexApiClient.SendRequestAsync] => Error Response URI:  - (0)

20:15:13 [Error] [PlexApiClient.SendRequestAsync] => Error Message: The request timed-out.

20:15:25 [Error] [PlexApiClient.GenerateResult] => PlexApi Error: Error on request to  (0) - : 

20:15:25 [Error] [PlexApiClient.GenerateResult] => : 

20:15:25 [Error] [PlexApiClient.GenerateResult] => StatusCode - 0:

**Comment by JasonLandbridge** [comment]
Yeah this is unfortunately still an issue in v0.9.0 but I will make it a goal to have it fixed in the next v0.9.1 release

**Comment by JasonLandbridge** [comment]
This has been fixed, see: https://github.com/PlexRipper/PlexRipper/issues/205
