### ISSUE TITLE
Cant see finish setup button

### ISSUE THREAD

**Issue by anthony0030** [PlexRipper/PlexRipper#96]
Half the interface is cut off and there is no way to scroll

Google Chrome
MacBook Pro 13 inch 2011

Regular
![PlexRipper](https://user-images.githubusercontent.com/13033263/139141461-2dd21922-8c7f-4060-9bdf-383987be1e9f.png)

Zoom at 80%
![PlexRipper (1)](https://user-images.githubusercontent.com/13033263/139141465-441a52c8-087c-4292-b263-444a12547f8b.png)

**Comment by JasonLandbridge** [comment]
This has been fixed in v0.9.0, will close now
