### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by GhostofGoes** [PlexRipper/PlexRipper#99]
Getting 500 internal server error when attempting to check server status or sync libraries. The IP and port are both valid from what's listed in Remote Access page on Plex. 

Originally I had Secure Connection set to Required and Strict TLS enabled, however PlexRipper is still failing even after setting Secure Connection to Preferred and disabling Strict TLS and restarting Plex.

Running the latest version of PlexRipper as of today (image ID 1785072563, v0.8.7) and the latest version of Plex (1.25.1.5286). This is running in Docker on Unraid 6.9.2. A friend's server that I don't manage is on 1.24.5.5173 and also has the same issue, so I feel like it's likely something to do with my configuration and not a Plex update.

Any idea what could cause this or tips on where I should start troubleshooting?

![plex_ripper_issue_cropped_stripped](https://user-images.githubusercontent.com/6599820/145339780-e2630485-a194-46fd-8786-c301ec3b70d4.jpg)

**Comment by funnelcloudservices** [comment]
Im seeing the same issue as well on two Plex servers.  Both are quite large.  It works fine for my little home Plex server but that has nothing on it I care to sync to.

**Comment by SgtBatten** [comment]
Same issue. Doesnt seem to be a way to point it to an LAN IP either?

**Comment by JasonLandbridge** [comment]
I'm slightly hoping this has been fixed in v0.9.0. @SgtBatten, could you try it in the new version and if it still happens, do you have some steps for me I can take to reproduce?

**Comment by SgtBatten** [comment]
> I'm slightly hoping this has been fixed in v0.9.0. @SgtBatten, could you try it in the new version and if it still happens, do you have some steps for me I can take to reproduce?

I managed to connect to my server. I had to manually specify a port and forward it through the router. Thet automatically generated port (not forwarded) was not working despite it allowing remote access perfectly fine. 

I have the no libraries issue now but will consider this particular one solved. Thanks

**Comment by JasonLandbridge** [comment]
Thanks for confirming, I'm fixing the setup loop and servers/libraries issue as we speak and then I will push a new release

**Comment by JasonLandbridge** [comment]
@SgtBatten, please keep an eye on this issue #108 as I will create something which will let you pick which connection you want to use for every server
